### ISSUE TITLE
BelongsToManyMultiSelect displays already attached options in dropdown on initial load

### ISSUE THREAD

**Issue by henninghorn** [filamentphp/filament#2363]
### Package

filament/filament

### Package Version

v2.12.2

### Laravel Version

v9.11.0

### PHP Version

PHP 8.1.4

### Bug description

When using the `BelongsToManyMultiSelect` component, already attached records are still displayed in the dropdown when the form is loaded initially.

With no records attached:
<img width="923" alt="billede" src="https://user-images.githubusercontent.com/742607/167787635-7ca6148e-7a24-4e06-a9b9-ba864e311b1d.png">

Attaching some records (selected options is removed from dropdown):
<img width="918" alt="billede" src="https://user-images.githubusercontent.com/742607/167787886-389682ab-3934-4adb-8f8a-6afc322f8ba8.png">

After having saved the new selection and then editing the list again:
<img width="921" alt="billede" src="https://user-images.githubusercontent.com/742607/167788270-bd74c8cf-3421-45d2-9a42-7e38b227f2bd.png">

I would expect the dropdown to exclude the already attached records to shown in the dropdown.

This is how I configure the field:

```php
// File: RolesRelationsManager.php
public static function form(Form $form): Form
{
    return $form
        ->schema([
            TextInput::make('label')->required(),
            TextInput::make('name')->required(),
            BelongsToManyMultiSelect::make('role_permissions')
                ->placeholder(__('Select permission(s) to be assigned to role'))
                ->preload()
                ->relationship(
                    'permissions',
                    'label',
                    fn (Builder $query, $livewire) => $query->whereBelongsTo($livewire->ownerRecord)
                )->columnSpan(2),
        ]);
}
```

This might be related to #1966.

### Steps to reproduce

Use a BelongsToManyMultiSelect to edit a belongsToMany relationship.

**Comment by danharrin** [comment]
Not related to #1966, btw.

**Comment by danharrin** [comment]
Please test #2377, the documentation for this feature is in the PR.

**Comment by ydjadii** [comment]
Any update ???

**Comment by zepfietje** [comment]
Is this still an issue? If so, could you set up a repository that allows us to reproduce the problem easily, @henninghorn?

**Comment by danharrin** [comment]
Yeah this is a confirmed issue

**Comment by SalvaTerol** [comment]
I have a similar problem, only using a normal select (not multiselect).

In my case it happens when I use options with searchable (and I don't use either getSearchResultsUsing or getOptionLabelUsing).

It basically duplicates the results:
<img width="615" alt="Captura de Pantalla 2022-09-18 a las 10 43 55" src="https://user-images.githubusercontent.com/35788666/190893688-f9579787-963c-4a2f-b041-1429989abe55.png">

<img width="636" alt="Captura de Pantalla 2022-09-18 a las 10 44 06" src="https://user-images.githubusercontent.com/35788666/190893694-6c3535ea-2f9a-4df5-b81a-5e0a80e4fedf.png">

<img width="927" alt="Captura de Pantalla 2022-09-18 a las 10 44 32" src="https://user-images.githubusercontent.com/35788666/190893696-e26c2b47-2723-4b3a-880a-585bec4425a4.png">

`Forms\Components\Select::make('technician_id')->options(User::role('technician')->pluck('name', 'id'))->searchable()->label('Técnico responsable'),`

When I can, I will share a repository with the example, as zepfietje says.

**Comment by danharrin** [comment]
Should be fixed by #4195, please verify in the next release

**Comment by RX-77IT** [comment]
Lately something seems to not be working right with MultiSelect and Many To Many relationship.

![original](https://i.imgur.com/YmDfIGs.jpg)

When i write something, all options already chosen with the same name disappear from the MultiSelect field and are transferred in the list below the field. However, if I save, all the original options present are still saved.

![written](https://i.imgur.com/sA7QzMo.jpg)

**Comment by RX-77IT** [comment]
> Can you share some code please @RX-77IT ?

It's just a simple many to many relationship between Product and Color models. The only thing that is somewhat different is the intermediate table name that is not in alphabetical order.

```
class ProductResource extends Resource
{
    ...
    public static function form(Form $form): Form
    {
        return $form
            ->schema([
                ...
                Forms\Components\MultiSelect::make('colors')
                    ->label('Colori associati al prodotto')
                    ->relationship('colors', 'name'),
                ...
            ]);
    }
    ...
}
```

```
class Product extends Model
{
    ...
    public function colors()
    {
        return $this->belongsToMany(Color::class, 'product_color');
    }
    ...
}
```

```
class Color extends Model
{
    ...
    public function products()
    {
        return $this->belongsToMany(Product::class, 'product_color');
    }
    ...
}
```

Feel free to ask anything else if you need.

**Comment by danharrin** [comment]
Reverted

**Comment by alexbirtwell** [comment]
following

**Comment by romansh** [comment]
I've encountered this too, following.

**Comment by danharrin** [comment]
Fixed in v3
