### ISSUE TITLE
Markdown editor doesn't get a red border upon validation errors

### ISSUE THREAD

**Issue by Cannonb4ll** [filamentphp/filament#2398]
### Package

filament/forms

### Package Version

v2.0.0

### Laravel Version

v9.0.0

### PHP Version

PHP 8.1

### Bug description

The markdown editor does not have a red border when a validation error occurs like inputs or selects.

Upon investigation with @danharrin we noticed `wire:ignore` is the cause of this:

https://github.com/laravel-filament/filament/blob/417e359c7023ed2b9cba319eb3529b16a456b47c/packages/forms/resources/views/components/markdown-editor.blade.php#L17

Removing that line fixes the $error state, but introduces a error within action modals.

**Comment by danharrin** [comment]
Can you test out #2398? There are a few other issues but most have been fixed I think

**Comment by Cannonb4ll** [comment]
As far as I can see and test seems all good!

**Comment by tanthammar** [comment]
#3649
