### ISSUE TITLE
Hard coded namespace on make commands.

### ISSUE THREAD

**Issue by iamine** [filamentphp/filament#2494]
### Package

filament/filament

### Package Version

v2.0

### Laravel Version

v9.0

### Livewire Version

v2.0

### PHP Version

PHP 8.0

### Bug description

namespace is hard coded on the commands, so if i change it in the config file will remain the same.

### Steps to reproduce

1. create a fresh laravel + filament project
2. publish filament config file.
3. change pages namespace
4. php artisan make:filament-page Example

the generated page will have the default namespace, App\\Filament\\Pages

**Comment by danharrin** [comment]
Decided that this feature isn't my biggest priority right now, if you'd like to submit a PR to add this then I would accept it. But there are lots of edge cases that you need to handle to be able to do it properly. It's not really a bug, you just need to move the files once they're created, it doesn't affect how your app runs.
