### ISSUE TITLE
Breadcrumbs do not update on Model change/update

### ISSUE THREAD

**Issue by typingbeaver** [filamentphp/filament#2530]
### Package

filament/filament

### Package Version

v2.12.7

### Laravel Version

v9.12.2

### PHP Version

PHP 8.1.0

### Bug description

There are issues with the breadcrumbs when updating the model, as they do not update on change.

This affects both **record title attribute** as well as the **route key** (Browser URL gets updated - e.g. from `categories/1/edit` to `categories/2/edit`, yet breadcrumb link still has old route key - e.g. `categories/1/edit`).

(Page title doesn't seem to update either.)

### Examples from filament demo

Before:
![Screenshot_20220524_165850](https://user-images.githubusercontent.com/74824542/170070212-d0201ee2-c23e-469a-9970-d64a150a635a.png)

After:
![Screenshot_20220524_165940](https://user-images.githubusercontent.com/74824542/170070352-a2f98ad2-31b4-4706-9e68-85a97ae9d9ac.png)

=> Breadcrumb still shows 'doloremque in laudantium' instead of 'changed record title'

### Steps to reproduce

1. Open edit page of an existing model.
2. Change record title attribute or route key attribute
3. Save changes

Title and/or url will update. Breadcrumb will still have old title and url anchor.

**Comment by LukasFreyCZ** [comment]
Maybe firing an event via livewire on update / save and using alpine to listen to it?

**Comment by danharrin** [comment]
Yeah I don't think this is a bug, if someone wants to PR it as a feature then they're more than welcome. I have no plans to though, so no point keeping this thread open.
