### ISSUE TITLE
Disabled Actions do not fire when initial state is false and subsequentially changes to true

### ISSUE THREAD

**Issue by titantwentyone** [filamentphp/filament#2614]
### Package

filament/tables

### Package Version

v2.12.22

### Laravel Version

v9.14.1

### Livewire Version

v2.10.5

### PHP Version

v8.1.6

### Bug description

This is related to an intial discuisson started in [#2563](https://github.com/laravel-filament/filament/discussions/2563).

If an action button is initially disabled and then subsequently enabled, any action associated with the newly enabled button is not fired.

I have set up an example repo up to quickly show the behaviour at https://github.com/titantwentyone/filament-issue-with-disabled. Just clone, seed and access Person resource in Filament (Filament login details: Username: "admin@filament.com" Password: "password")

### Steps to reproduce

Based on the repo provided:

1. Got to the "Person" resource.
2. When the page is loaded and "flag" is true, both buttons can be clicked to make "flag" toggle between true and false.
3.  When the page is loaded and "flag" is false, the first button will toggle "flag" between true and false but the second button, when enabled, will not fire its action.

Some GIFs to aid in understanding the issue:

Correct behaviour:
![filament-correct-behaviour](https://user-images.githubusercontent.com/1583366/171129448-fde63c20-13b6-4c86-94d6-90462e7c6411.gif)

Incorrect behaviour
![filament-incorrect-bahviour](https://user-images.githubusercontent.com/1583366/171129496-2dfc01fd-9bdd-4082-98f8-2ba90e933a03.gif)

**Comment by danharrin** [comment]
This is caused by a Livewire bug, conditionally adding wire:click to an element breaks it

Demo: https://laravelplayground.com/#/snippets/7fd69cb2-961e-41d1-81da-a63de73fdf0a

**Comment by danharrin** [comment]
We can fix it with a workaround - #3148

**Comment by titantwentyone** [comment]
Awesome! Works a treat. Thanks Dan!
