### ISSUE TITLE
BelongsToSelect doesn't preload all possible models if you allow duplicates

### ISSUE THREAD

**Issue by mokhosh** [filamentphp/filament#2715]
### Package

filament/filament

### Package Version

v2.12.28

### Laravel Version

v9.17.0

### Livewire Version

v2.10.5

### PHP Version

php 8.1

### Bug description

I have a `belongsToSelect` where I want to allow duplicates since I have another column that differentiates between duplicates. This is what my table looks like:
- bank_id
- client_id
- booking_center
filament seemed to need an `id` field as well so I added that (can we not have this required?)

Now the problem is when I set `$allowsDuplicates` to `true` I am able to search and find duplicates and add them, but they don't show up in my preloaded select box when I have `$shouldPreloadAttachFormRecordSelectOptions` set to `true`.

Also I've added a unique key to mysql for the three column combination so when I try to add a duplicate with all three columns matching I get an exception. Where can I add the validation to avoid this?

**Comment by danharrin** [comment]
Does #2706 fix this?

**Comment by zepfietje** [comment]
@danharrin, should we close this as inactive? We also don't have a reproduction repo.

**Comment by mokhosh** [comment]
sorry, just checked and it is fixed.
thanks.
