### ISSUE TITLE
Searchable select components lose any order given

### ISSUE THREAD

**Issue by webtimal** [filamentphp/filament#2771]
### Package

filament/forms

### Package Version

v2.12.31

### Laravel Version

v9.17.0

### Livewire Version

v2.6

### PHP Version

PHP 8.1.5

### Bug description

The `searchable()` method on a Select component seems to break the options' ordering. Probably due to the usage of the ChoicesJS library as they are being rendered in the correct order in the view file initially.

This works as intended:
```
Components\Select::make('client_id')
   ->options(
      Client::orderBy('full_name', 'desc')->get()
         ->pluck('full_name', 'id')
   )
```
![Bild_2022-06-15_021548407](https://user-images.githubusercontent.com/33128507/173710230-1ec917bc-98d3-4c1e-9e8d-4f30807c5f8d.png)

whereas this doesn't
```
Components\Select::make('client_id')
   ->options(
      Client::orderBy('full_name', 'desc')->get()
         ->pluck('full_name', 'id')
   )
   ->searchable()
```
![Bild_2022-06-15_020224813](https://user-images.githubusercontent.com/33128507/173708992-e3fcbd9e-8635-4a47-a8d8-02d88d7481a3.png)

I think it would be useful to have a method for providing a column name to sort by.

**Comment by wychoong** [comment]
https://github.com/laravel-filament/filament/issues/683#issuecomment-961801569
