### ISSUE TITLE
Page's Action modal form with FileUpload field

### ISSUE THREAD

**Issue by invaders-xx** [filamentphp/filament#2772]
### Package

filament/filament

### Package Version

v2.12.31

### Laravel Version

v9.17.0

### Livewire Version

v2.10.5

### PHP Version

PHP 8

### Bug description

I am using an action within ListRecord's page to import files:
```php
Action::make('import')
                ->label(__('Import'))
                ->action(function (array $data): void {
                    ray($data);
                    $this->notify('success', __('Imported'));
                })
                ->form([
                    Forms\Components\Select::make('company_id')
                        ->label(__('Company'))
                        ->validationAttribute(__('Company'))
                        ->searchable()
                        ->options(fn() => Company::internal()->pluck('name', 'id')->toArray())
                        ->required(),
                    Forms\Components\Toggle::make('as_new')
                        ->label(__('As new')),
                    Forms\Components\FileUpload::make('files')
                        ->label(__('Files'))
                        ->panelLayout('grid')
                        ->validationAttribute(__('Files'))
                        ->multiple()
                        ->acceptedFileTypes(['application/json'])
                ])
```

When validating the form, I have the following messages in the console:
<img width="660" alt="image" src="https://user-images.githubusercontent.com/604907/173760071-3c2040a2-e907-4374-a8a5-2db9ace174d1.png">

If I remove the FileUpload field, no error in console

**Comment by ryangjchandler** [comment]
@invaders-xx Your img tag is in the code block btw.

**Comment by themahdavi** [comment]
What happens ?!!
You hack github 😂
markdown crashed

**Comment by danharrin** [comment]
I fixed it

**Comment by ryangjchandler** [comment]
@invaders-xx See #956 for more information.

**Comment by invaders-xx** [comment]
@ryangjchandler thanks Ryan, if I understand well (which is not always the case with English) it means that we have to live with this console output ?

**Comment by ryangjchandler** [comment]
@invaders-xx Yeah, we can't see a problem on our end. It seems to be a LW problem.

**Comment by danharrin** [comment]
Yeah this is a Livewire problem, thankfully it has no consequences to the usability of the action
