### ISSUE TITLE
ActionGroup creates scrollable overflow and hides below table

### ISSUE THREAD

**Issue by kamilst96** [filamentphp/filament#2783]
### Package

filament/filament

### Package Version

v2.13.2

### Laravel Version

v9.17

### Livewire Version

v2.10.5

### PHP Version

PHP 8.1.7

### Bug description

Expanded ActionGroup is restricted to table container's bounds, so any potential overflow creates scrollbar and actions are pushed under it. Picture below:

1:
![Zrzut ekranu z 2022-06-15 22-38-33](https://user-images.githubusercontent.com/37311362/173922662-9d2dd4b7-45f0-44cf-ad1f-6f8fe163b9d1.png)

2:
![Zrzut ekranu z 2022-06-15 22-30-52](https://user-images.githubusercontent.com/37311362/173921845-4a49d853-fb52-47e2-9e3d-8196a220264b.png)

### Steps to reproduce

- Create action group and add actions to it
- Propagate enough data for table to render
- Open ActionGroup in table's last row/record

**Comment by michalcharvat** [comment]
Can confirm this issue too. Problem is related to class .overflow-y-auto on div which covers the table. 
<img width="689" alt="image" src="https://user-images.githubusercontent.com/8058273/175611607-67cd2610-7dce-49fa-90e0-6a678b89f8f8.png">

**Comment by saade** [comment]
waiting for #2879
