### ISSUE TITLE
table multiselect filter spawns infinite requests to getSelectOptionLabels

### ISSUE THREAD

**Issue by ainesophaur** [filamentphp/filament#2815]
### Package

filament/tables

### Package Version

v2.13.4

### Laravel Version

v9.17.0

### Livewire Version

v2.10.5

### PHP Version

PHP 8.1.4

### Bug description

When using a `MultiSelectFilter` on a table there seems to be a never ending loop of requests to livewire from the client for the action `getSelectOptionLabels` after the multi select filter is opened. Closing the filter dialog (popup or above produces the same) does not stop the current request or the never ending loop. I've been able to reproduce the issue using either static options or a relationship for the select filter. I have a .har file with all the requests if needed.

Below is a screen cap. The first filter selected is a regular `SelectFilter` which does not start the death loop. The second filter is a `MultiSelectFilter` which triggers the death loop. The calls to the server for `getSelectOptionLabels` will not stop until you refresh or leave the page. 

![filters_gone_wild](https://user-images.githubusercontent.com/4686198/174395171-cddbfd67-33da-493e-b4c0-91f63d9fa127.gif)

### Steps to reproduce

```php
use Livewire\Component;
use Filament\Tables;
class TicketTable extends Component implements Tables\Contracts\HasTable
{
    use Tables\Concerns\InteractsWithTable;
    
    ///...other code
    
    protected function getTableFilters(): array
    {
        return [
            Tables\Filters\MultiSelectFilter::make('ticket_status_id')
            ->label('Ticket Status')
            ->relationship('ticketStatus', 'name'),
        ];
    }
}
```

**Comment by danharrin** [comment]
Which Alpine & Livewire versions are you using?

**Comment by ainesophaur** [comment]
Alpine 3.10.2 and Livewire 2.10.5

**Comment by danharrin** [comment]
Just checked, I can't replicate this myself. 2 XHR requests are made each time I select a new option, which is expected. Please provide a repo to reproduce this issue with.

**Comment by ainesophaur** [comment]
Considering my implementation of select options is inherently incorrect (based on the feedback from #2250) its quite possible I created the loop. I'm going to take the suggestions from #2250 and implement them. I'll report back with either a sample project or confirmation that there is no bug.

**Comment by ainesophaur** [comment]
Closing out as it as the suggestions from #2250 resolves the issue here.
