### ISSUE TITLE
Select->searchable() cursor and input not showing

### ISSUE THREAD

**Issue by Nick-Kyle-Wonde** [filamentphp/filament#2865]
### Package

filament/forms

### Package Version

v2.11.12

### Laravel Version

v9.11.0

### Livewire Version

v2.10.5

### PHP Version

8.1.5

### Bug description

https://user-images.githubusercontent.com/92025133/174784920-2019ad02-2cdc-4239-b4ba-79fb0dfecf10.mov

When using a select component with the searchable() function the input text and cursor do not show on screen.

The search works and the result is selected, but you cannot see the input.

This issue is not present when using the multiselect component.

I believe the issue was introduced here https://github.com/laravel-filament/filament/pull/1769

### Steps to reproduce

use Filament\Forms\Components\Select;

Select::make('example')->options([
      'draft' => 'Draft',
      'review' => 'In review',
      'published' => 'Published',
   ])->searchable()

**Comment by Nick-Kyle-Wonde** [comment]
With reference to https://github.com/laravel-filament/filament/pull/1769/files

Updating line 100 from
'w-full bg-white truncate cursor-text',
to
'flex-auto bg-white truncate cursor-text',

And updating  line 116 from
'w-0 grow p-0 border-0 focus:ring-0 focus:outline-none',
to
'flex-auto p-0 border-0 focus:ring-0 focus:outline-none',

**Comment by zepfietje** [comment]
@Nick-Kyle-Wonde, can you check if this is still an issue? If so, which browser are you using? As I can't reproduce it so far.

**Comment by ryangjchandler** [comment]
Also looks like you're using a custom theme, have you rebuilt it recently?

**Comment by danharrin** [comment]
Looks like they're using the form builder, so yeah rebuilding the assets might fix it

**Comment by Nick-Kyle-Wonde** [comment]
I've updated to the latest version of forms and rebuilt. That has taken care of the issue. Thanks for your responses.
