### ISSUE TITLE
groupby in Resource Lists breaks sorting / pagination

### ISSUE THREAD

**Issue by simonbuehler** [filamentphp/filament#2895]
### Package

filament/tables

### Package Version

v2.13.9

### Laravel Version

v9.18

### Livewire Version

v2.10.5

### PHP Version

8.0.2

### Bug description

Grouping a Participant Resource by day of 'registered_at' datetime field to get counts of registered users by day breaks sorting on last page of pagination

### Steps to reproduce

[demo repo](https://github.com/simonbuehler/bug_demo2)

**Comment by zepfietje** [comment]
Thanks for the reproduction repo!

I'm currently looking into the issue and what I found is that when you refresh the page (when you're on the second page), it does show records correctly.

**Comment by zepfietje** [comment]
The record key is used on table rows to prevent DOM diffing issues. Your code returns the string 'id' for every record, which leads to the `wire:key` on all table rows being the same. If you update this to be a unique value, everything works fine. So for example:

```php
public function getTableRecordKey(Model $record): string
{
    return $record->date;
}
```

**Comment by simonbuehler** [comment]
thanks for clarifying, i took the `TableRecordKey` as the _column name_ of the key, not the individual value, awesome!

**Comment by khanakia** [comment]
<img width="959" alt="Screenshot 2023-01-20 at 5 08 24 PM" src="https://user-images.githubusercontent.com/2174170/213686559-58ade455-ed7d-4749-8de1-7978fffc67bd.png">
Getting Compatibility error. Any suggestion how to fix it ?
