### ISSUE TITLE
Create Customer Bugs

### ISSUE THREAD

**Issue by suman-codeclouds** [filamentphp/filament#2898]
### Package

filament/filament

### Package Version

have no idea 

### Laravel Version

have no idea

### Livewire Version

have no idea

### PHP Version

have no idea

### Bug description

![image](https://user-images.githubusercontent.com/107020441/175222319-8c932c59-7685-46a1-840f-75b88f6b53e1.png)
As you can see in the above image the date of birth calendar allows us to select future dates right? it should not be allowed to us. it should be disabled in the calendar.

**Comment by danharrin** [comment]
Please open issues about the demo in the filamentphp/demo repo in the future
