### ISSUE TITLE
Repeater defaults not working for Toggle/Select form components

### ISSUE THREAD

**Issue by ndijkstra** [filamentphp/filament#2914]
### Package

filament/filament

### Package Version

v2.13.10

### Laravel Version

9.18

### PHP Version

8.1

### Bug description

When setting a default array for the Repeater component, the defaults of a Toggle and Select component are not set. For TextInput components in the repeater it is working.

### Steps to reproduce

```
Forms\Components\Repeater::make('boards')
                        ->orderable('sort_order')
                        ->default([['title' => 'The title is working' 'visible' => true, 'options' => 'option2']])
                        ->schema([
                                Forms\Components\TextInput::make('title')->required(),
                                Forms\Components\Toggle::make('visible'),
                                Forms\Components\Select::make('options')
                                    ->options([
                                        'option1' => 'Option 1',
                                        'option2' => 'Option 2',
                                    ])
                        ]),
```

**Comment by ndijkstra** [comment]
> It works if you move the default value to each input instead of having them as an array in the repeater like: `Forms\Components\Toggle::make('visible')->default(true),`

Thanks, but I want to set the defaults dynamically so I cant use it like that.

**Comment by zepfietje** [comment]
Can you provide us a reproduction repository URL and then we'll look at your issue? That would allow us to download it and review your bug much easier, so it can be fixed quicker. Please make sure to give us some instructions on where to find the bug, and include a database seeder with everything we need to set it up quickly.

**Comment by danharrin** [comment]
Hey, could you check if #3495 fixes this and doesnt introduce more issues?

**Comment by tanakei1102** [comment]
I also encountered the same issue. While the `default` method didn't work for me in my environment (v2.17.48), I was able to achieve it using `afterStateHydrated`. Here is an example for your reference:

```php
Components\Repeater::make('stores')->label('stores')
    ->schema([
        Components\Select::make('store')->label('Store')
            ->options(\App\Models\Store::all()->pluck('name', 'id')->toArray())
            ->preload()
            ->reactive()
            ->afterStateUpdated(function ($state, callable $set) {
                $set('departments', []);
            }),
        Components\Select::make('departments')->label('Departments')
            ->multiple()
            ->searchable(false)
            ->options(function (callable $get) {
                $store = \App\Models\Store::find($get('store'));
                if (empty($store)) {
                    return [];
                }
                return $store->departments->pluck('name', 'id');
            }),
    ])
    ->required()
    ->minItems(1)
    ->columns(2)
    ->afterStateHydrated(function ($state, callable $set) {
        $set('stores', [['store' => 1, 'departments' => [1, 2]]]);
    })
```

**Comment by danharrin** [comment]
Probably because defaults only fill on the Create page and you're on the Edit page?

**Comment by bilogic** [comment]
I have removed all traces of `->fill(...)` from my page, but the repeater still loads with 0 items even though I specified `->defaultItems(3)`

**Comment by ashkesarmaa** [comment]
@bilogic  I have the same issue any updates? my repeater loads with 0 items and i have to press add to list item button to see the first item even though I specified ->defaultItems(1)  for it

**Comment by winex01** [comment]
i have a custom action modal both for create/edit and the ->defaultItems(1) doesnt worked. im using this as alternative:

```
->afterStateHydrated(function ($component, $state) {
    // When editing: if no data is loaded, create 1 empty row.
    if (blank($state)) {
        $component->state([[]]);
    }
})
```
