### ISSUE TITLE
Reactive field within a modal refresh the resource's table

### ISSUE THREAD

**Issue by invaders-xx** [filamentphp/filament#2942]
### Package

filament/filament

### Package Version

v2.13.11

### Laravel Version

v9.17.0

### Livewire Version

v2.10.5

### PHP Version

PHP 8

### Bug description

I have a modal with a reactive select field and each time I update the select, we see the table refreshing in the background. See video

https://user-images.githubusercontent.com/604907/175971683-b737fc73-5c46-435a-b25f-a0c8c43c6fb0.mp4

**Comment by ryangjchandler** [comment]
This is because the modal isn't it's own Livewire component and the state is held inside of the same component as the table, so a reactive field will trigger an entire re-render of the component. This isn't a bug, more of a side effect.
