### ISSUE TITLE
Passing null to parameter #1 ($json) of type string is deprecated in Pages/Concerns/HasActions.php on line 52

### ISSUE THREAD

**Issue by matick-beeping** [filamentphp/filament#2967]
### Package

filament/filament

### Package Version

v2.13.7

### Laravel Version

v9.17.0

### Livewire Version

v2.10.5

### PHP Version

PHP 8.1.6

### Bug description

I have a resource view page with custom action defined:

```
protected function getActions(): array
    {
        return [
            Actions\EditAction::make(),
            Action::make('sendOfferEmail')
                ->label('Send Offer')
                ->icon('heroicon-s-mail')
                ->action('sendOfferEmail')
                ->requiresConfirmation(),           
        ];
    }
```

and inside the file I have my custom action method defined, where I do my business logic. When I click the button to trigger the action (after confirmation) I get this deprecation error in my deprecation log:

`[2022-06-29 10:03:08] local.WARNING: json_decode(): Passing null to parameter #1 ($json) of type string is deprecated in /var/www/html/vendor/filament/filament/src/Pages/Concerns/HasActions.php on line 52  
`

### Steps to reproduce

Create a custom action with call to your custom method in resource view page

### Relevant log output

```shell
[2022-06-29 10:03:08] local.WARNING: json_decode(): Passing null to parameter #1 ($json) of type string is deprecated in /var/www/html/vendor/filament/filament/src/Pages/Concerns/HasActions.php on line 52
```

**Comment by danharrin** [comment]
Fixed by #2971
