### ISSUE TITLE
MediaPolicy@delete => false does not hide filepond delete button

### ISSUE THREAD

**Issue by ziming** [filamentphp/filament#2992]
### Package

filamentphp/filament

### Package Version

2.13.14

### Laravel Version

9

### Livewire Version

2

### PHP Version

8.1

### Bug description

Given that I'm not able to figure out how to move the filepond download button to the right side (given how close they are), I decided that I should disable the delete button for the SpatieMediaUploadField in my admin

1st I tried to find a ->disableDelete() method but I could not find it, so I decided to go to my MediaPolicy delete() method and return false.

However, the delete button is still there.

**Comment by danharrin** [comment]
This isn't a bug, it's just not a feature yet. Feel free to PR it in, else you will have to wait for someone else to contribute.
