### ISSUE TITLE
The "category" field breaks after changing the payment method

### ISSUE THREAD

**Issue by heloufir** [filamentphp/filament#3000]
When I change the plugin type from **Not paid** to **Paid** and return to **Not paid** the `category` field breaks, take a look to the demo video below.

https://user-images.githubusercontent.com/6197875/176866253-c1246f49-61bf-40bd-8d9f-8f7b0882d8a2.mp4

**Comment by ArtMin96** [comment]
I also have that problem.

**Comment by danharrin** [comment]
Does #3410 fix your issues?
