### ISSUE TITLE
Dependant select issue in filament/forms v2.13

### ISSUE THREAD

**Issue by Ariziky** [filamentphp/filament#3009]
### Package

filament/forms

### Package Version

v2.13

### Laravel Version

v9.11

### Livewire Version

v2.10

### PHP Version

PHP 8.1.0

### Bug description

Hi. Dependent selection does not work in recent version of filament/forms. I used it well in the v2.12 version before the package upgrade.

**Comment by danharrin** [comment]
Can you send example code please?

**Comment by Ariziky** [comment]
Select::make('application_id')
                                            ->label('Application')
                                            ->required()
                                            ->placeholder('Sélectionnez une application')
                                            ->options(Application::query()->pluck('title', 'id'))
                                            ->searchable()
                                            ->reactive()
                                            ->afterStateUpdated(function (\Closure $set) {
                                                $set('roles', null);
                                            }),

                                        MultiSelect::make('roles')
                                            ->label('Profil')
                                            ->required()
                                            ->placeholder('Sélectionnez un profil')
                                            ->options(function (\Closure $get) {
                                                $application = Application::query()->find($get('application_id'));
                                                if (! $application) {
                                                    return Role::query()->pluck('name', 'id');
                                                }
                                                return $application->roles->pluck('name', 'id');
                                            })
                                            ->searchable()


I am using roles by application.

**Comment by danharrin** [comment]
Please check if the latest release fixes this issue

**Comment by danharrin** [comment]
I've just checked this and I am fairly certain that the example I tried works. Make sure you call `$this->form->fill()` in `mount()` if you dont already.

If its still broken, please send code that I can use to replicate the issue. I do not have access to your models, so hard code arrays for me.

**Comment by ridlafalah** [comment]
Select::make('division_id')
->label('Division Name')
->required()
->options(
[
'draft' => 'Draft',
'a' => 'a',
'b' => 'b',
]
)
->searchable()
->reactive()
->afterStateUpdated(fn (callable $set) => $set('segment_id', null)),

Select::make('segment_id')
->label('Segment Name')
->required()
->options(function (callable $get) {
$division = $get('division_id');
if ($division == 'draft') {
return ['asd' => 'asd'];
}
return [];
})
->searchable()
->reactive(),

**Comment by Ariziky** [comment]
Hi, that issue has been solved for me in the current version. Thanks

**Comment by ridlafalah** [comment]
> Hi, that issue has been solved for me in the current version. Thanks

can you share your current filament version info, thanks.

**Comment by Ariziky** [comment]
I'm using version 14.4.
