### ISSUE TITLE
beforeDelete and afterDelete hooks are not working

### ISSUE THREAD

**Issue by goigarg** [filamentphp/filament#3010]
### Package

filament/filament

### Package Version

2

### Laravel Version

9

### PHP Version

8.1

### Bug description

beforeDelete and afterDelete hooks are not firing in EditRecord

**Comment by danharrin** [comment]
Please share your Page class code

**Comment by danharrin** [comment]
Try `->before()` and `->after()` callbacks on the Action object. I've updated the docs.
