### ISSUE TITLE
Console error on resource's relation edit/view

### ISSUE THREAD

**Issue by invaders-xx** [filamentphp/filament#3042]
### Package

filament/filament

### Package Version

v2.13.21

### Laravel Version

v9.19.0

### Livewire Version

v2.10.6

### PHP Version

PHP 8.1

### Bug description

I have a weird bug and I would like to know if it's a known one : in a resource's relation when I click on edit, it's fine. then I click on view it's fine and then if I click again on edit I have a console error : 
```
Uncaught TypeError: Cannot read properties of undefined (reading 'value')
    at Proxy.getTabs (eval at <anonymous> (module.esm.js:471:14), <anonymous>:12:51)
    at Proxy.init (eval at <anonymous> (module.esm.js:471:14), <anonymous>:8:29)
    at module.esm.js:457:23
    at H (module.esm.js:434:3)
    at module.esm.js:2622:27
    at Function.<anonymous> (module.esm.js:1152:55)
    at a (module.esm.js:582:95)
    at module.esm.js:720:47
    at Array.forEach (<anonymous>)
    at module.esm.js:720:27
```
The form is empty. It happens on every resource's relations whatever I have in the form
Please see video

https://user-images.githubusercontent.com/604907/177570436-b43a19e0-6114-46e8-b8b4-7a3245371766.mp4

### Relevant log output

```shell
VM15318:12 Uncaught TypeError: Cannot read properties of undefined (reading 'value')
    at Proxy.getTabs (eval at <anonymous> (module.esm.js:471:14), <anonymous>:12:51)
    at Proxy.init (eval at <anonymous> (module.esm.js:471:14), <anonymous>:8:29)
    at module.esm.js:457:23
    at H (module.esm.js:434:3)
    at module.esm.js:2622:27
    at Function.<anonymous> (module.esm.js:1152:55)
    at a (module.esm.js:582:95)
    at module.esm.js:720:47
    at Array.forEach (<anonymous>)
    at module.esm.js:720:27
getTabs @ VM15318:12
init @ VM15318:8
(anonymous) @ module.esm.js:457
H @ module.esm.js:434
(anonymous) @ module.esm.js:2622
(anonymous) @ module.esm.js:1152
a @ module.esm.js:582
(anonymous) @ module.esm.js:720
(anonymous) @ module.esm.js:720
(anonymous) @ module.esm.js:211
(anonymous) @ module.esm.js:211
S @ module.esm.js:210
(anonymous) @ module.esm.js:146
module.esm.js:416 Alpine Expression Error: tab is not defined

Expression: "tab === '-general-tab'"

 
```

**Comment by invaders-xx** [comment]
It also happens with view buttons and then create. It occurs also on a simple form with select inputs

**Comment by zepfietje** [comment]
Can you provide us a reproduction repository URL and then we'll look at your issue?

That would allow us to download it and review your bug much easier, so it can be fixed quicker. Please make sure to give us some instructions on where to find the bug, and include a database seeder with everything we need to set it up quickly.

**Comment by danharrin** [comment]
Hey, I think this is just a Livewire dom-diffing conflict with Alpine unfortunately, but luckily I don't think it affects the functionality of Filament. Thanks for the report.

**Comment by shivaRamdeen** [comment]
@danharrin any particular remedy available?
