### ISSUE TITLE
n+1 in MultiSelectFilter

### ISSUE THREAD

**Issue by mohammad2306** [filamentphp/filament#3123]
### Package

filament/filament

### Package Version

2.13.24

### Laravel Version

9.19

### Livewire Version

2

### PHP Version

8

### Bug description

hi, using MultiSelectFilter with relationship load all categories (where not working) and with option n+1 problem

```php
Tables\Filters\MultiSelectFilter::make('category_id')
                    ->options(Category::where('type', Category::TYPE_CLUB)->get()->pluck('title', 'id')),
                    
public function category(): BelongsTo
    {
        return $this->belongsTo(Category::class)
                    ->where('type', Category::TYPE_CLUB);
    }
```
![image](https://user-images.githubusercontent.com/61474718/179073446-de498034-b4fa-40d7-8ee1-99d50a34358d.png)

**Comment by zepfietje** [comment]
@mohammad2306, could you set up a repository with the minimal code needed to reproduce the problem? This allows us to fix the issue much quicker.

**Comment by mohammad2306** [comment]
@zepfietje 
https://github.com/mohammad2306/filament-filter
run php artisan migrate --seed and check category filter in news resource

**Comment by zepfietje** [comment]
@mohammad2306, this is not a bug.
The many queries are caused by the filter options being retrieved internally.
You should wrap your options query in a closure, and then it's fixed!

```diff
 Tables\Filters\MultiSelectFilter::make('category_id')
+    ->options(fn () => Category::where('type', Category::TYPE_NEWS)->get()->pluck('title', 'id')),
-    ->options(Category::where('type', Category::TYPE_NEWS)->get()->pluck('title', 'id')),
```
