### ISSUE TITLE
File upload (from user experience perspective)

### ISSUE THREAD

**Issue by x-ahmed** [filamentphp/filament#3191]
### Package

filament/forms

### Package Version

v2.14.3

### Laravel Version

v9.3.0

### Livewire Version

v2.10.6

### PHP Version

PHP 8.1.6

### Problem description

When a user uploaded a file and then reverts that file without uploading another (supposing that the element has nullable equals to true) and then clicks the save button, the (FileUpload) component's state keeps stuck with the value of the reverted file.

### Expected behavior

If a user reverted the uploaded file and then clicks save, the upload state should be null.

### Steps to reproduce

![Screenshot from 2022-07-21 08-57-48](https://user-images.githubusercontent.com/63619368/180149995-356c0e73-47ab-4e2a-8b2b-9b76ef05fb84.png)

**Comment by zepfietje** [comment]
Can you provide us a reproduction repository URL and then we'll look at your issue?

That would allow us to download it and review your bug much easier, so it can be fixed quicker. Please make sure to give us some instructions on where to find the bug, and include a database seeder with everything we need to set it up quickly.

**Comment by x-ahmed** [comment]
Hey, here it is a [repo](https://github.com/x-ahmed/file-upload-issue-reproduction/) with steps to reproduce the issue :)

**Comment by zepfietje** [comment]
Thanks, @x-ahmed. We will shortly look into your issue!

**Comment by danharrin** [comment]
Hello, fixed this in #3593. Unfortunately, your proposed solution breaks multi-file uploads, as it completely resets the state of the field.
