### ISSUE TITLE
Escape quotes in actions

### ISSUE THREAD

**Issue by Simoneu01** [filamentphp/filament#3213]
### Package

filament/filament

### Package Version

v2.14.4

### Laravel Version

9.21.6

### Livewire Version

v2.10.6

### PHP Version

8.1.8

### Problem description

The quote broke the page, Action does not escape the single quote. Similar to this old issue: #952

### Expected behavior

That the usage of the quote doesn't break the page

### Steps to reproduce

Create a view page of a resources and add this block:

```php
protected function getActions(): array
    {
        return array_merge(
            parent::getActions(),
            [
                Action::make("Dai l'accesso")
                    ->color('success')
                    ->action('givePriorityAccess'),
            ]
        );
    }
```

### Relevant log output

```shell
Uncaught SyntaxError: missing ) after argument list
    at new Function (<anonymous>)
    at Directive.value (wire-directives.js:93:24)
    at Directive.get (wire-directives.js:64:33)
    at processLoadingDirective (LoadingStates.js:96:20)
    at LoadingStates.js:22:13
    at Array.forEach (<anonymous>)
    at LoadingStates.js:21:27
    at MessageBus.js:17:13
    at Array.forEach (<anonymous>)
    at MessageBus.value (MessageBus.js:16:38)
```

**Comment by danharrin** [comment]
Don't use the `make()` method to pass the label, that should be used for a unique ID instead.

Try passing `label('Dai l\'accesso')` instead and give the action a one-word name

**Comment by Simoneu01** [comment]
Thank you! It's working!
