### ISSUE TITLE
Issue with fields overlapping when zooming in

### ISSUE THREAD

**Issue by AlexJames-Dev** [filamentphp/filament#3226]
### Package

filament/filament

### Package Version

v2.14.5

### Laravel Version

v9.21.6

### Livewire Version

v2.10.6

### PHP Version

8.1.7

### Problem description

When zooming in using the browser zoom function, the fields overlap the side bar

https://user-images.githubusercontent.com/43570309/180766137-55e30dc5-3839-4eac-acc0-a664b4f534a2.mp4

### Expected behavior

The side bar should hide itself or the bars should shrink to match the new viewport size

### Steps to reproduce

Create a filament project, add a resource, go into the create view and zoom in

**Comment by zepfietje** [comment]
@AlexJames-Dev, it seems like your navigation bar is broken. Have you by any chance published the views?

**Comment by AlexJames-Dev** [comment]
@zepfietje I knew i'd missed something... yeah i had the base view published as i needed to add in a script tag for my livechat widget and couldnt figure out how to add the additional flags like data-key into the Filament::registerScripts function! Many thanks

**Comment by zepfietje** [comment]
Seems like [render hooks](https://filamentphp.com/docs/2.x/admin/appearance#render-hooks) is what you're looking for! It's generally not advised to publish the views.

**Comment by AlexJames-Dev** [comment]
@zepfietje That looks like exactly what im after! Note to self, read the docs in their entirety! Thanks very much for the help, greatly appreciated!
