### ISSUE TITLE
I have problem in. running filament

### ISSUE THREAD

**Issue by zainabalanjawy** [filamentphp/filament#3227]
### Package

filament/filament

### Package Version

v2.14.5 

### Laravel Version

v8.0.0

### Livewire Version

v2.0.0

### PHP Version

PHP 8.0.0

### Problem description

I got this error 
 Package filament/filament has requirements incompatible with your PHP version, PHP extensions and Composer   
  version:                                                                                                     
    - filament/filament v2.14.5 requires php ^8.0 which does not match your installed version 7.3.29.    

my mac have already php 8 version and the project is also on php 8 but i dont know why I got this problem. If you please give me detailed steps 

### Expected behavior

my mac have already php 8 version and the project is also on php 8 but i dont know why I got this problem. If you please give me detailed steps 

### Steps to reproduce

my mac have already php 8 version and the project is also on php 8 but i dont know why I got this problem. If you please give me detailed steps 

### Reproduction repository

-

**Comment by zainabalanjawy** [comment]
I have installed it on my Mac already

**Comment by danharrin** [comment]
You may have installed it, but your CLI is probably still running an old version

**Comment by zainabalanjawy** [comment]
How should I let my cli run a specific version of php?

**Comment by zepfietje** [comment]
> How should I let my cli run a specific version of php?
> […](#)

Depends on how you've installed PHP (using Homebrew for example). If you perform a Google search for your exact setup, I bet you'll find it! 😄
