### ISSUE TITLE
prepare_inherited_attributes in HR confict merge x-show

### ISSUE THREAD

**Issue by Wit3** [filamentphp/filament#3238]
### Package

filament/tables

### Package Version

v2.15.0

### Laravel Version

v9.21.6

### Livewire Version

v2.10.6

### PHP Version

PHP v8.1.8

### Problem description

The x-show attribute it's merged not correctly in this method

https://github.com/filamentphp/filament/blob/ea3e195ed6068dd61aeef09f9fcb269edc9c2c09/packages/tables/resources/views/index.blade.php#L253

this duplicate attribute generated by the method `prepare_inherited_attributes ` i filament support doens't merge correctly the custom x-show property ( maybe it's the camel case compared).

```html
<div aria-hidden="true" class="border-t filament-hr" xshow="@js($isReorderable || $isSearchVisible || $isColumnToggleFormVisible) || selectedRecords.length" x-show="@js($isReorderable || $isSearchVisible || $isColumnToggleFormVisible) || selectedRecords.length"></div>
```
causing this error
```
Alpine Expression Error: Invalid or unexpected token

Expression: "@js($isReorderable || $isSearchVisible || $isColumnToggleFormVisible) || selectedRecords.length"

 div.border-t.filament-hr
```

### Expected behavior

merge correctly x-show

### Steps to reproduce

Normal rerder of table component ( no admin )

**Comment by Wit3** [comment]
hi @danharrin 
if table use

```php
    protected function getTableFiltersLayout(): ?string
    {
        return Layout::AboveContent;
    }
```

alpine has error
```console
Alpine Expression Error: Invalid or unexpected token

Expression: "@js($isReorderable || $isSearchVisible || $isColumnToggleFormVisible) || selectedRecords.length"

 div.border-t.filament-hr
```

**Comment by danharrin** [comment]
This was fixed, maybe the fix has not been released yet

**Comment by Wit3** [comment]
v2.15.4 fix this issue, thanks dan
