### ISSUE TITLE
Reordering with filtered records breaks consistency

### ISSUE THREAD

**Issue by simonbuehler** [filamentphp/filament#3241]
### Package

filament/tables

### Package Version

v2.15.1

### Laravel Version

 9.21.6

### PHP Version

8.1.7

### Problem description

When operating on a subset of the records ( filtered/searched ) the reordering breaks the unique sort column

https://user-images.githubusercontent.com/78061/180987017-62dd3546-a9e1-41dc-b9d2-e8a7d23df251.mp4

### Expected behavior

operate on all records (unfiltered) to ensure consistency

### Steps to reproduce

see vid

**Comment by pxlrbt** [comment]
This is not a bug, but a feature. People explicitly wanted to order subsets based on active filters.

**Comment by pxlrbt** [comment]
As a fix for your use-case, you could probably overwrite `public function toggleTableReordering()` to also reset your filters.
