### ISSUE TITLE
Table alpine invalid character @

### ISSUE THREAD

**Issue by G3z** [filamentphp/filament#3247]
### Package

filament/tables

### Package Version

v2.15.3

### Laravel Version

v9.22.0

### Livewire Version

v2.10.6

### PHP Version

PHP 8.1.8

### Problem description

this appears in the browser console
```
[Warning] Alpine Expression Error: Invalid character: '@' (app.js, line 1)

Expression: "@js($isReorderable || $isSearchVisible || $isColumnToggleFormVisible) || selectedRecords.length"

 – 
<div aria-hidden="true" class="border-t filament-hr dark:border-gray-700" x-show="@js($isReorderable || $isSearchVisible || $isColumnToggleFormVisible) || selectedRecords.length"></div>

<div aria-hidden="true" class="border-t filament-hr dark:border-gray-700" x-show="@js($isReorderable || $isSearchVisible || $isColumnToggleFormVisible) || selectedRecords.length"></div>
[Error] SyntaxError: Invalid character: '@'
	(funzione anonima) (app.js:1:4394)
```	
the relevant line seems to be:
https://github.com/filamentphp/filament/blob/2.x/packages/tables/resources/views/index.blade.php#L253
but i'm not sure why

### Expected behavior

no error :)

### Steps to reproduce

any table shows this issue

**Comment by danharrin** [comment]
Fixed in #3253
