### ISSUE TITLE
Pivot table not loaded on BelongsToMany relation manager causes crash when updating the model

### ISSUE THREAD

**Issue by innocenzi** [filamentphp/filament#3258]
### Package

filament/tables

### Package Version

2.13.0-beta1

### Laravel Version

9.21.1

### Livewire Version

2.6

### PHP Version

8.1.8

### Problem description

When saving an edit form of a `RelationManager` for a `BelongsToMany` relationship, an error is thrown (see below for the logs).

The issue is that the `pivot` attribute is not loaded for the record. So when trying to access it like the following, it would not work: 

```php
if (count($pivotColumns)) {
    $record->{$relationship->getPivotAccessor()}->update($pivotData);
}
```

I'm not sure why the pivot is not loaded, I have not dived very deep in Filament's code. My relationship is simple, it looks like that:

```php
public function crew(): BelongsToMany
{
    return $this->belongsToMany(CrewMember::class, 'leg_crew')
        ->withPivot('role');
}
```

When calling `crew()`, I do have the pivot loaded with the expected data, but it is not there in the `$record` from `EditAction`. The underlying query might be wrong.

### Expected behavior

The pivot for a `BelongsToMany` relationship should be loaded and saving the model should work without throwing.

### Steps to reproduce

- Create a resource and add a relation manager with a `BelongsToMany` relationship
- Edit a record and save

### Relevant log output

```shell
[2022-07-26 13:53:39] local.ERROR: Call to a member function update() on null {"userId":2,"exception":"[object] (Error(code: 0): Call to a member function update() on null at /Users/enzoinnocenzi/Code/http/captainjet/vendor/filament/tables/src/Actions/CreateAction.php:67)
```

**Comment by zepfietje** [comment]
Can you provide us a reproduction repository URL and then we'll look at your issue?

That would allow us to download it and review your bug much easier, so it can be fixed quicker. Please make sure to give us some instructions on where to find the bug, and include a database seeder with everything we need to set it up quickly.

**Comment by innocenzi** [comment]
Closing this for now because I don't have time yet for a reproduction repository. I'll reopen with a reproduction as soon as I can.
