### ISSUE TITLE
Suddenly all class declaration is sanatized in hint settings

### ISSUE THREAD

**Issue by ekandreas** [filamentphp/filament#3259]
### Package

filament/forms

### Package Version

v2.13.16

### Laravel Version

v9

### Livewire Version

v2

### PHP Version

8.1

### Problem description

All helpertext and hints now removes inserted "class" in the html text.
The function "sanitizeHtml" is introduced that removes all class declarations. That is really bad for formatting...

### Expected behavior

We want to format the hint and helpertext with classes as before, please remove sanitizeHtml or make it possible to add raw content, please!

### Steps to reproduce

Just set a hint to a field with class property and see it vanish.

**Comment by ekandreas** [comment]
The file that introduces this bug: resources/views/components/field-wrapper/index.blade.php, row 42

**Comment by zepfietje** [comment]
@ekandreas, could you include a code example of what you're trying to set as hint? Not too sure if I understand what you mean by "class property".

Clear examples help us to fix the issue quicker.

**Comment by ryangjchandler** [comment]
@zepfietje I believe he had `class=""` in the hint itself.

**Comment by zepfietje** [comment]
> @zepfietje I believe they had `class=""` in the hint itself.

Ah that could be the case. But then you must be passing an entire HTML element to the hint? It's by design that hints can render Markdown, but you should not be able to pass any custom HTML in there. What do you think, @ryangjchandler?

**Comment by ryangjchandler** [comment]
Do we not allow passing HtmlString objects? That is all opt-in unsafety, which in my opinion is fine.

**Comment by danharrin** [comment]
We allow markdown without HtmlString, we need to support class attributes as they are not a security risk

**Comment by danharrin** [comment]
Fixed by #3322.
