### ISSUE TITLE
TimePicker does not show value after saving form

### ISSUE THREAD

**Issue by mendizalea** [filamentphp/filament#3306]
### Package

filament/filament

### Package Version

v.2.15.4

### Laravel Version

v.9.22.1

### PHP Version

PHP 8.1.6

### Problem description

When a TimePicker is added inside a repeater, the value is not shown once the form is saved. If a refresh is made, it is displayed correctly.

It only fails when an update is done, when create it works fine.

I have tried changing the DatePicker with a TextInput and it works correctly.

### Expected behavior

Show the value once the form is saved without having to refresh.

### Steps to reproduce

```
public static function form(Form $form): Form
{
	return $form
		->schema([
		Section::make('General')
		   ->schema([
			  Forms\Components\Grid::make()
				 ->schema([
					TextInput::make('name')
					   ->rule('required'),
				 ])
		   ])->columnSpan([
			  'sm' => 2,
		   ]),
			Section::make('Prueba')
		   ->schema([
			  Forms\Components\Grid::make()
				 ->schema([
					Repeater::make('times')
					   ->relationship()
					   ->schema([
						  TimePicker::make('time')
							 ->withoutSeconds()
							 ->rule('required')
							 ->reactive()
							 ->columnSpan([
								'md' => 3,
							 ]),
					   ])
					   //->createItemButtonLabel('Add New Machinery')
					   ->dehydrated()
					   ->defaultItems(0)
					   ->disableLabel()
					   ->columns([
						  'md' => 9,
					   ])
					   ->columnSpan([
						  'md' => 2,
					   ]),
				 ])
		   ])->columnSpan([
			  'sm' => 2,
		   ]),
		]);
}
```

### Reproduction repository

https://github.com/mendizalea/filament-datapicker-bug

**Comment by zepfietje** [comment]
I can reproduce this issue.

However, I'm not yet sure how to fix it.
It seems the field's state gets reset on saving the edit form.
Any idea, @danharrin? Since you built the date picker originally.

**Comment by danharrin** [comment]
This bug is not present in the latest release of Filament.
