### ISSUE TITLE
Package tgalopin/html-sanitizer is abandoned

### ISSUE THREAD

**Issue by neopheus** [filamentphp/filament#3313]
### Package

Other

### Package Version

2.x

### Laravel Version

v9.0.0

### PHP Version

PHP 8.1

### Problem description

Hi,

Package tgalopin/html-sanitizer is abandoned, you should avoid using it. Use symfony/html-sanitizer instead.

Used in https://github.com/filamentphp/support

### Expected behavior

no errors

### Steps to reproduce

composer update

### Reproduction repository

https://github.com/filamentphp/support

**Comment by ryangjchandler** [comment]
Reopening as it's a valid issue and doesn't require reproduction.

**Comment by danharrin** [comment]
We cannot use symfony/html-sanitizer as it requires minimum PHP 8.1. We will move to this package in the next major version, but that package was built off of the one we are using currently.

**Comment by ryangjchandler** [comment]
@danharrin Pretty sure we can use Symfony 6.0 instead of 6.1. 6.0 is what Laravel 9 uses and that is PHP 8.0.

**Comment by danharrin** [comment]
Nope, this is a new Symfony package

**Comment by ryangjchandler** [comment]
Ah, I see.
