### ISSUE TITLE
when FileUpload and DatePicker in modal form, local language don't  load

### ISSUE THREAD

**Issue by pslxx** [filamentphp/filament#3327]
### Package

filament/forms

### Package Version

v2.15.5

### Laravel Version

V9

### Livewire Version

2.10

### PHP Version

8.1

### Problem description

when using action modal form
fileupload  and datetime component can't push scripts to stack

### Expected behavior

load language

### Steps to reproduce

Action::make('test')->form([
                       Forms\Components\DatePicker::make('date')
                    ])

### Reproduction repository

-

**Comment by zepfietje** [comment]
We need a public Git repository which contains a Laravel app with the minimal amount of Filament code to reproduce the problem. That would allow us to download it and review your bug much easier, so it can be fixed quicker. Please make sure to include a database seeder with everything we need to set the app up quickly.

**Comment by danharrin** [comment]
Anyway, duplicate of #2835
