### ISSUE TITLE
Unable to create resource 

### ISSUE THREAD

**Issue by KiritoXD01** [filamentphp/filament#3343]
### Package

filament/filament

### Package Version

v2.15.6

### Laravel Version

v9.22.1

### PHP Version

8.1.3

### Problem description

When I try to create a new resource I get the following error, I'm running the proyect on Laravel Sail

![image](https://user-images.githubusercontent.com/46627083/182245620-8ee984e9-ff7f-4b62-b5df-b474c7ed01b7.png)

I tried publishing all stubs but is not working

### Expected behavior

I expect to create a new resource

### Steps to reproduce

- Installed Filament on a brand new project
- ran `php artisan make:filament-resource User`

### Reproduction repository

Not available at the moment

**Comment by danharrin** [comment]
Very sorry about this, a fix is on the way.

**Comment by danharrin** [comment]
I've just released the fix, sorry about that.
