### ISSUE TITLE
Action submitted before confirmed

### ISSUE THREAD

**Issue by NathanaelGT** [filamentphp/filament#3361]
### Package

filament/filament

### Package Version

v2.15.11

### Laravel Version

v9.23.0

### Livewire Version

v2.10.6

### PHP Version

PHP 8.1.2

### Problem description

If we have actions with `->submit(...)`  and `->requiresConfirmation()`, when the action is clicked, it submits before the user confirm

### Expected behavior

it submits after the user confirms

### Steps to reproduce

Clone the [reproduction repository](https://github.com/NathanaelGT/filament-issue_action-submitted-before-confirmed), install the dependencies, migrate and seed.
Login with this credentials
```
email: admin@mail.com
password: password
```

Open todo edit page, then click "Complete"

### Reproduction repository

https://github.com/NathanaelGT/filament-issue_action-submitted-before-confirmed

**Comment by danharrin** [comment]
You need to remove `->submit('save')`
