### ISSUE TITLE
Multi-Select relationship query triggered 3 times with preload()

### ISSUE THREAD

**Issue by ajnsn** [filamentphp/filament#3372]
### Package

filament/forms

### Package Version

v2.15.12

### Laravel Version

v9.19

### Livewire Version

v2.6

### PHP Version

PHP 8.1.8

### Problem description

Its not rather a bug but might be a performance issue as a `relationship()`-query is executed 3 times if you `preload()` the relationship.

We are using various relationships which do not have too many records, e.g. user roles typically are not too many, and the `preload()` is very handy to speed up user expierence.

Unfortunately the default behaviour is that these queries are executed 3 times, see screenshot.

![roles](https://user-images.githubusercontent.com/13928621/182797757-a0386bea-af22-4d6e-8a3d-c6971048678c.png)

We can work around the issue but not using the `relationship()` and instead building your own select with a single executed query ... with the downside that we have to care about saving the relationship manually :).

```php
Forms\Components\MultiSelect::make('roles')
    ->options(Role::pluck('name', 'id'))
```

### Expected behavior

The query is only executed once?

### Steps to reproduce

Clone the reproduction repository
Create a Filament user
Add a role in Filament
Go the the EditUser page and look into the debugbar output

### Reproduction repository

https://github.com/ajnsn/filament-select-test

**Comment by danharrin** [comment]
I believe that if you use `->options(fn () => Role::pluck('name', 'id'))` it only gets executed once. Correct?

**Comment by ajnsn** [comment]
`->options(Role::pluck('name', 'id'))` will also already work.

**Comment by danharrin** [comment]
Very odd. What about if you use `relationship()` first and then `options()` on top?

**Comment by ajnsn** [comment]
```php
Forms\Components\MultiSelect::make('roles')
    ->relationship('roles', 'name')
    ->options(Role::pluck('name', 'id')),
```

Thanks Dan, this works fine - instead of `preload()`

**Comment by ajnsn** [comment]
fyi, this brings the described multiple queries behaviour back: 

```php
Forms\Components\MultiSelect::make('roles')
    ->relationship('roles', 'name')
    ->options(fn () => Role::pluck('name', 'id')),
```

**Comment by danharrin** [comment]
Investigated this, and you're not gonna like the answer 😂 

We pass the options to the `@js` directive, which transforms the array into a JS object.

Livewire overrides the `@js` directive that Laravel includes, as Livewire supported `@js` before Laravel did, and it's a "legacy" thing to support it in old Laravel versions.

Now, unlike Laravel's `@js` that only evaluates the options once, Livewire's version evaluates it 3 times 😬

So Livewire should really just save the evaluated value once instead and then this will be fixed!

**Comment by ajnsn** [comment]
Thanks @danharrin for taking the time, good find!

I tested within the peproduction repository. [First](https://github.com/ajnsn/filament-select-test/commit/70314e049521506ddd4d23ded03cb6a35edeb12d) without Livewire's @js registration. I also found this [PR](https://github.com/livewire/livewire/pull/4876) and [applied](https://github.com/ajnsn/filament-select-test/commit/84a240d44087a9e4ff75ebcb1e43186e3e6d7f97) the approach introduced there. Both work and reduce the query to 1. 

So let's keep an eye on the PR. I do not know if Caleb is already back from his paternity leave?!

**Comment by danharrin** [comment]
He is back, but working on Livewire v3, not v2 at all (AFAIK). I'll send him a message next week to give him a nudge to merge the PR. I'd rather not add any technical debt to Filament itself involving fixing the issue our end.

**Comment by danharrin** [comment]
I nudged him as promised, the PR is merged, and should be released shortly.

**Comment by ajnsn** [comment]
Thank you !!!

**Comment by ajnsn** [comment]
Can confirm that this is fixed by updating Livewire. Thanks again!
