### ISSUE TITLE
Reactive/lazy not properly working on DateTimePicker

### ISSUE THREAD

**Issue by sweebee** [filamentphp/filament#3381]
### Package

filament/forms

### Package Version

v2.15.12

### Laravel Version

v9.23.0

### Livewire Version

v2.10.6

### PHP Version

8.0.20

### Problem description

When you make a DateTimePicker reactive it keeps closing on every action you make in the picker. When you select a date it closes, when you change the hour/minute it closes.

https://user-images.githubusercontent.com/10496485/182912068-39997d89-60fe-42d5-a74f-e8a5035abb95.mov

### Expected behavior

Picker shouldn't be closed when changing the date/time. It's working fine on v2.13.27 but since v2.13.28 its broken.

### Steps to reproduce

See attached repository.

```php
protected function getFormSchema(): array
    {
        return [
            Forms\Components\DateTimePicker::make('date')->reactive(),
            Forms\Components\TextInput::make('title')->visible(fn(Closure $get) => $get('date')),
        ];
    }
```

### Reproduction repository

https://github.com/sweebee/filament-datetimepicker-bug

**Comment by zepfietje** [comment]
Thanks for the detailed report, @sweebee!

Looking at the changes in the date time picker component, and the version you found, I think it's caused by a9bad2c4d285857769c070adceb3df1625aa563e.

@awcodes, since you implemented that change, do you have any idea about the cause?

**Comment by awcodes** [comment]
@zepfietje there were changes after this. The changes in https://github.com/filamentphp/filament/commit/a9bad2c4d285857769c070adceb3df1625aa563e were replaced with the new alpine floating ui directive syntax. I'm not sure why this commit would have broken it. 

Dan did do some work on the JS for the date picker before the final implementation of the floating ui directive syntax.

I can do some more digging though.
