### ISSUE TITLE
Color Picker loosing the value if used inside the Repeater

### ISSUE THREAD

**Issue by ManojKiranAppathurai** [filamentphp/filament#3421]
### Package

filament/filament

### Package Version

2.15

### Laravel Version

9.19

### PHP Version

8.1.1

### Problem description

When I used the color picker inside the `Repeater` component all the previous color picker field that has value is becoming null on adding new item.

### Expected behavior

All the existing state should be maintained across the network

### Steps to reproduce

After setting up the project locally follow the below steps.

1. Go to user create page
2. Try to add multiple items in `Preferred Colors` Repeater field
3. On adding new items you can see all the previous value are disappearing

### Reproduction repository

https://github.com/ManojKiranAppathurai/filament-color-picker-issue

**Comment by danharrin** [comment]
Does #3402 fix this?

**Comment by zepfietje** [comment]
> I am using the latest filament version. I think it doesn't fix the issue

The fix in that PR hasn't been released yet in a new Filament version. Could you set `dev-2.x` as your Filament version in `composer.json` as see if the issue still occurs, @ManojKiranAppathurai?

**Comment by zepfietje** [comment]
> you mean `2.x-dev`

Whoops sorry, yeah:

```json
"filament/filament": "2.x-dev",
```

**Comment by danharrin** [comment]
Please investigate the issue yourself and provide a PR fix if you can :)

**Comment by danharrin** [comment]
I cannot replicate this issue in the latest Filament verison

https://user-images.githubusercontent.com/41773797/184987137-1adbc16b-5bb7-4a6d-9ce6-0dd5977df4f3.mov
