### ISSUE TITLE
Filter dropdown and toggle column dropdown in mobile 

### ISSUE THREAD

**Issue by Valpuia** [filamentphp/filament#3477]
### Package

filament/tables

### Package Version

2.0

### Laravel Version

9.19

### PHP Version

8.1

### Problem description

Table filter and toggleable dropdown not showing properly on mobile view. 
![Screenshot from 2022-08-11 14-54-57](https://user-images.githubusercontent.com/28250303/184103534-dc24fb1f-466c-4496-83a6-9a2d4eb8cae9.png)

### Expected behavior

to show dropdown as visible (responsive) for mobile

### Steps to reproduce

demo from docs

### Reproduction repository

https://demo.filamentphp.com/shop/orders

**Comment by danharrin** [comment]
Duplicate of #3418
