### ISSUE TITLE
Markdown editor not show characters correctly on RTL

### ISSUE THREAD

**Issue by themahdavi** [filamentphp/filament#3481]
### Package

filament/forms

### Package Version

2.15.18

### Laravel Version

9.24

### Livewire Version

2.10.7

### PHP Version

8.1.7

### Problem description

This problem accord when using markdown editor into Grid and RTL base locale
shown like this :
![image](https://user-images.githubusercontent.com/31320104/184193047-45b1d81b-dfc5-4186-9c2f-a0cf6a365996.png)

after testing some changes find problem but don't know how to solve that
 

### Expected behavior

If use MarkdownEditor in Grid with columns on specific screen break and change locale to RTL base locale like `fa` or `ar` on `config/app.php` issue shown

### Steps to reproduce

1- clone repository
2- under `database` folder have `database.sqlite` file just have users table with one record
3-change `.env.example` to `.env` or own .env file with sqlite database driver
4- nothing to do just run project and go to Edit page of user and see on bio field

### Reproduction repository

https://github.com/themahdavi/markdown-problem

**Comment by danharrin** [comment]
Chrome-only issue.

**Comment by danharrin** [comment]
Fixed by #3526. Let's see what other issues that change introduces, I can't find other effects of this change.
