### ISSUE TITLE
Unable to set attribute name for any input

### ISSUE THREAD

**Issue by HazJ** [filamentphp/filament#3520]
### Package

filament/filament

### Package Version

2.15.18

### Laravel Version

9.24.0

### Livewire Version

2.10.7

### PHP Version

8.1.7

### Problem description

I am unable to set the attribute name on any input. Both of these don't work for me.

```
                            ->label('attribute-name')
                            ->validationAttribute('attribute-name')
```

### Expected behavior

I expect the input to use the specified attribute name.

### Steps to reproduce

See the **README** in the repository here:
[github.com/HazJ/validation-attribute-name/](https://github.com/HazJ/validation-attribute-name/)

As a quick test, I added an input outside of a repeater. The issue appears there as well.

<img width="1090" alt="Screenshot 2022-08-16 at 12 42 00" src="https://user-images.githubusercontent.com/20573863/184849709-55c9d11f-fb63-43b2-bd2b-ad3cca113344.png">

### Reproduction repository

https://github.com/HazJ/validation-attribute-name/

**Edit:** For what I am trying to do, I can work around it by using $get, however it seems like a bug to me. I expect the attribute name to be used, and in a repeator too.
The value field is required

Repeator:
The value.0 is required
The value.1 is required
The value.2 is required

**Comment by danharrin** [comment]
Just debugged this, it's just Laravel behaviour I think...

```php
use Illuminate\Support\Facades\Validator;

Validator::make([
  'value' => null,
], [
  'value' => ['required'],
], [], [
  'value' => 'label',
])->errors()->first();

Validator::make([
  'value' => 'foo',
], [
  'value' => [
    function (string $attribute, $value, Closure $fail) {
      if ($value === 'foo') {
        $fail("The $attribute is invalid.");
      }
    },
  ],
], [], [
  'value' => 'label',
])->errors()->first();
```

The `$attribute` is always the name of the raw property where the data is stored, not the custom validation attribute label.

**Comment by Sheldon-Knight** [comment]
had a similar problem  then saw that my lang en file was missing for some reason so i created a new project paste that files back and it worked

**Comment by Sheldon-Knight** [comment]
move you lang en file inside resources
