### ISSUE TITLE
Tabbing navigation not working in modals on initial load

### ISSUE THREAD

**Issue by hxnk** [filamentphp/filament#3543]
### Package

filament/tables

### Package Version

v2.15.19

### Laravel Version

v9.25.1

### Livewire Version

v2.10.17

### PHP Version

8.1.6

### Problem description

Tabbed navigation in modal forms doesn't work when the modal loads for the first time. When closing the modal and opening it again it works as expected.

### Expected behavior

Tabbed navigation works on initial modal load

### Steps to reproduce

1. Open a customer on the Filament Demo
2. Click "New Address" button
3. Try to tab to next focusable input

See: https://demo.filamentphp.com/shop/customers/1/edit?activeRelationManager=0

### Reproduction repository

https://github.com/filamentphp/demo

**Comment by hxnk** [comment]
@danharrin Not sure why the bot closed this issue. I chose to add the filament demo repository as reproduction repo, it proves the bug is there.

Can you check please?

**Comment by danharrin** [comment]
Yeah, I will reopen manually, thank you for the clarification. It closes the issue when the user fills in a Filament repo as some people are lazy and dont want to reproduce the issue by themselves, and just link to the Filament repo instead of helping is out, even though the issue isnt in the demo :(

**Comment by danharrin** [comment]
I've got no clue why this happens, I have looked into it. Have you looked into it?

**Comment by hxnk** [comment]
@danharrin I hadn't looked at it yet, but I just did, and it's fixed in #3604, but don't ask me why :grin:

**Comment by danharrin** [comment]
Wow, I would never have thought of that lol
