### ISSUE TITLE
create page shows 404 

### ISSUE THREAD

**Issue by maxzod** [filamentphp/filament#3554]
### Package

filament/filament

### Package Version

v2.0

### Laravel Version

9.19

### Livewire Version

2.5

### PHP Version

8.0.2

### Problem description

 ![image](https://user-images.githubusercontent.com/47630729/185463445-cf825397-fce1-4933-bb4e-60b4d5b664fd.png)

### Expected behavior

to work fine with any order its a array 

### Steps to reproduce

if i listed the pages in this order it shows the above screenshot
```php
    public static function getPages(): array
    {
        return [
            'view' => Pages\ViewCategory::route('/{record}'),
            'index' => Pages\ListCategories::route('/'),
            'create' => Pages\CreateCategory::route('/create'),
            'edit' => Pages\EditCategory::route('/{record}/edit'),
        ];
    }
```

but if i move the view to bottom 
it works just fine ! 
```php
  public static function getPages(): array
    {
        return [
            'index' => Pages\ListCategories::route('/'),
            'create' => Pages\CreateCategory::route('/create'),
            'edit' => Pages\EditCategory::route('/{record}/edit'),
            'view' => Pages\ViewCategory::route('/{record}'),
        ];
    }
```

### Reproduction repository

n/a

**Comment by danharrin** [comment]
This is because view is a wildcard route, so captures the create request first. It's the behaviour of Laravel's router.

**Comment by maxzod** [comment]
@danharrin 
 
i think if  you re ordered the getPages array to make it place the `view` in the end of it it will work

**Comment by danharrin** [comment]
Yes

**Comment by maxzod** [comment]
ok , i will work on it
