### ISSUE TITLE
Default values gone

### ISSUE THREAD

**Issue by ekandreas** [filamentphp/filament#3567]
### Package

filament/forms

### Package Version

2.15.19

### Laravel Version

v9

### Livewire Version

v2

### PHP Version

8.1

### Problem description

When upgrading from forms v2.15.18 to 19 all default values to fields are gone.

### Expected behavior

We want the fields to have default values filled.

### Steps to reproduce

Just use default values, via states.

### Reproduction repository

https://github.com

**Comment by ekandreas** [comment]
You can't be serious?

**Comment by danharrin** [comment]
We have tests that cover default values being filled, and we've had no other reports of issues from other users. Thus, we need a reproduction repo. It even says on the issue template, that the issue will be closed if no repo is provided.

**Comment by ekandreas** [comment]
Well then I have to setup a specific repo for you 👎 
afterStateHydrated doesn't work as expected in version 2.15.19. Everything regarding afterStateHydrated is fine in 2.15.18.

**Comment by danharrin** [comment]
Yes, you have to set up a repo for us, so we can help you. For free 🙂

**Comment by danharrin** [comment]
Out of pure interest, I tried using `default()` and `afterStateHydrated()` myself, as well as checking that our tests are passing. I discovered no issues.

You have provided no other reproduction information apart from "all default values to fields are gone", which really isn't useful to us? Even if you did still omit the reproduction URL, we wouldn't be able to help you

**Comment by ekandreas** [comment]
I will come back to you with a repo that reproduces the issue. But it will take me some days.
