### ISSUE TITLE
Multitenancy is not working

### ISSUE THREAD

**Issue by Valpuia** [filamentphp/filament#3569]
### Package

filament/filament

### Package Version

v2

### Laravel Version

v9

### Livewire Version

v2

### PHP Version

8.1

### Problem description

I try to use filamentPHP and [stancl/tenancy](https://tenancyforlaravel.com/docs/v3/introduction/). In the documentation it is mention like

> To set up [stancl/tenancy](https://tenancyforlaravel.com/docs) to work with Filament, you just need to add the InitializeTenancyByDomain::class middleware to [Livewire](https://tenancyforlaravel.com/docs/v3/integrations/livewire) and the [Filament config file](https://filamentphp.com/docs/2.x/admin/installation#publishing-the-configuration):

doc link [filament multitenancy](https://filamentphp.com/docs/2.x/admin/resources/getting-started#stancltenancy).

But error prompt when I add 'InitializedTenancyByDomain' on both 'config/livewire' and 'config/filament'.

Errors are:
1. After putting the `InitializeTenancyByDomain::class` on both config file the central domain admin not accessible "error: tenant could not be verified"
2. tenant domain can access '/admin/login' and other functionality

### Expected behavior

1. Only central domain can access filament admin panel
2. Tenant domain should not access the admin panel

### Steps to reproduce

1. download the link
2. composer install
3. migrate and serve laravel
4. try to go to url/admin

### Reproduction repository

[https://github.com/Valpuia/filament-multi-tenant](https://github.com/Valpuia/filament-multi-tenant)

### Relevant log output

```shell
None
```

**Comment by zepfietje** [comment]
@Valpuia, make sure to properly set up access to the admin panel: https://filamentphp.com/docs/2.x/admin/users#authorizing-access-to-the-admin-panel.

**Comment by Valpuia** [comment]
Hi @zepfietje as per your comment I change the filament user in User model and tenant cannot access admin anymore. but it does not solve the problem no 1. If I put `InitializeTenancyByDomain::class` in `config/filament.php` and on the central domain it is given `Tenant could not be identified on domain localhost`

**Comment by zepfietje** [comment]
@Valpuia, are you sure this is an issue with Filament? It sounds like a problem with the tenancy package.

**Comment by abanghendri** [comment]
Hi, I know it was closed but I still get issue with stancl/tenancy
I use single-database multitenancy and manual intialization (not using subdomain/domain/path), thus I make a `tenant_id` column in my users table, and modify login behaviour adding these lines to authenticate method
```
$tenant = auth()->user()->tenant;
tenancy()->initialize($tenant);
```
but unfortunately, it seems not working, when I visiting dashboard and add custom widget or resource, I put some tenancy info with `tenant()` helper, it always return null, so I need to add manual initialization again and again over every resources/widget

I don't know why it happen
please help me
