### ISSUE TITLE
Unnecessary queries on list page

### ISSUE THREAD

**Issue by anatolyeltsov** [filamentphp/filament#3578]
### Package

filament/filament

### Package Version

v2.15.20

### Laravel Version

v9.3.4

### PHP Version

PHP 8.1.8

### Problem description

Unnecessary queries. That wasn't the case at least on version 2.15.11.

### Expected behavior

No unnecessary queries.

### Steps to reproduce

Noticed it in my project and reproduced on clean install:

1. Install latest versions of Laravel, Filament and Laravel Debugbar
2. Create Test model and it's migration with console (with only id and timestamps)
3. Create TestResource with console (with no additional changes)
4. Everything is ok when there are no rows in database for this model
5. Add one row into database
6. There are two additional queries in Debugbar
![screenshot-127 0 0 1_8001-2022 08 19-22_40_40](https://user-images.githubusercontent.com/54027342/185698637-e68b9a6f-6b6c-4503-b5b6-1fbc1c479a7e.png)
7. Add another row into database
8. Now we have four strange queries
![screenshot-127 0 0 1_8001-2022 08 19-23_08_51](https://user-images.githubusercontent.com/54027342/185699419-0b0ff470-f99c-4636-9489-d39e65a6729d.png)

 

### Reproduction repository

https://github.com/anatolyeltsov/filament-queries

**Comment by raphael-evolutap** [comment]
i'm having this problem too

**Comment by danharrin** [comment]
Thanks, fixed by #3592.
