### ISSUE TITLE
[CSS Issue] dark mode not working as expacted

### ISSUE THREAD

**Issue by egyjs** [filamentphp/filament#3613]
### Package

filament/filament

### Package Version

v2.14.22

### Laravel Version

v9.25.1

### PHP Version

V8.1

### Problem description

i have a multi select component  
its working well in light mode, but in dark mode it's not

### Expected behavior

in light mode: 
![image](https://user-images.githubusercontent.com/12745270/185952638-631d75e7-4559-4c31-8a6d-d1331651c21a.png)
in dark mode:
![image](https://user-images.githubusercontent.com/12745270/185952755-b5573cb6-36a7-49a1-9031-9b38a62727d8.png)
### Expected behavior:
the choices text must be in light, Cuz the background is dark 

### Steps to reproduce

.

### Reproduction repository

.

**Comment by danharrin** [comment]
Your custom Tailwind color palette has contrasting issues I think
