### ISSUE TITLE
 MultiSelectFilter break on L8.x

### ISSUE THREAD

**Issue by Eighke** [filamentphp/filament#3647]
### Package

filament/tables

### Package Version

v2.15.24

### Laravel Version

v8.83.23

### PHP Version

PHP 8.1

### Problem description

Following the implementation of the [Filter indicators](https://github.com/filamentphp/filament/pull/3599/) MultiSelectFilter are broken when using Laravel 8.

Simple reason: `Arr:join` doesn't exists on Laravel 8, it's come from Laravel 9.

https://github.com/filamentphp/filament/pull/3599/files#diff-480fef5e7837495da1a3b5e620e71c32fc2067f5e2b883fa82c1c742863777ffR37

### Expected behavior

Not having 500 :D

### Steps to reproduce

* Add a `MultiSelectFilter`
* Filter anything
* 500 `Method Illuminate\Support\Arr::join does not exist.`

### Reproduction repository

None

**Comment by danharrin** [comment]
Whoops! Will fix this.

**Comment by danharrin** [comment]
2b8703b8468911c3f56e8b661e0c2b3c0f296b16
