### ISSUE TITLE
DatePicker doesn't reset to null

### ISSUE THREAD

**Issue by Frameck** [filamentphp/filament#3650]
### Package

filament/forms

### Package Version

v2.15.18

### Laravel Version

v8.83.23

### Livewire Version

v2.10.7

### PHP Version

PHP 8.0.21

### Problem description

When the user check a toggle i need to set a DatePicker to the current date (this works), but the opposite doesn't, so when the toggle is unchecked the DatePicker wont't reset to null.

### Expected behavior

The DatePicker should reset it's value to null

### Steps to reproduce

`DatePicker::make('account_deactivation_date')
    ->displayFormat('d/m/Y'),
Toggle::make('retire_account')
    ->required()
    ->reactive()
    ->afterStateUpdated(function (Closure $set, $state) {
        if ($state) {
            $set('account_deactivation_date', now());
        } else {
            // here should set the empty value
            $set('account_deactivation_date', null); 
        }
    }),`

### Reproduction repository

https://github.com

**Comment by danharrin** [comment]
Should be fixed by #4197.
