### ISSUE TITLE
Image Column ->extraImgAttributes() doesnt add class attribute

### ISSUE THREAD

**Issue by sawirricardo** [filamentphp/filament#3667]
### Package

filament/tables

### Package Version

v2.15.23

### Laravel Version

v9.25.1

### Livewire Version

v2.10

### PHP Version

PHP 8.1.9

### Problem description

I put on `->extraImgAttributes(['class' => 'some class'])` in the SpatieMediaLibraryColumn, specifically ImageColumn, however, it doesnt output the class

problems may be due to an existing @class([]), which havent yet consider the incoming class attributes from extraImgAttributes

### Expected behavior

the class got merged / applied

### Steps to reproduce

```
Tables\Columns\SpatieMediaLibraryImageColumn::make('images')
->extraImgAttributes(['class' => 'rounded-md shadow-md'])
```

### Reproduction repository

https://github.com/sawirricardo/filament-bugs

**Comment by danharrin** [comment]
Fixed by #3670.
