### ISSUE TITLE
Dynamically Enabling MarkdownEditor does not work. 

### ISSUE THREAD

**Issue by yaplej** [filamentphp/filament#3692]
### Package

filament/filament

### Package Version

v2.15.26

### Laravel Version

v9.7.0

### Livewire Version

v2.3

### PHP Version

PHP 8.1.4

### Problem description

When dynamically disabling & enabling a MarkdownEditor the components, buttons, textbox do not become active when its dynamically enabled.

### Expected behavior

It should behave like the RichEditor.

### Steps to reproduce

Make a RichEditor that is enabled & disabled dynamically verify it works.  Change it to a MarkdownEditor.

### Reproduction repository

https://github.com/yaplej/DynamicMarkdownEditor

**Comment by marky291** [comment]
@yaplej The link to reproduce does not work

**Comment by yaplej** [comment]
@marky291 Its a private repository.

**Comment by ryangjchandler** [comment]
@yaplej The reproduction repository needs to be public for us to access it and debug the problem.

**Comment by yaplej** [comment]
@ryangjchandler I had already added @marky291 but also went ahead and made it public.

**Comment by marky291** [comment]
Can you maybe let us know what file and line to look at? 😂

**Comment by yaplej** [comment]
@marky291 Look at the behavior of the Markdown vs Rich editor when they are enabled/disabled.

https://github.com/yaplej/DynamicMarkdownEditor/blob/main/app/Filament/Resources/ChangeRequestResource.php#L44-L60

**Comment by danharrin** [comment]
Confirmed, can only fix in v3 when we switch to a different markdown editor though. The reason why this doesn't work is because we need a `wire:ignore` to wrap around the entire editor.

**Comment by danharrin** [comment]
Fixed in v3.

**Comment by nlvedwin** [comment]
> 

it seems broken again @danharrin for the rich editor markdown works fine tho.

**Comment by danharrin** [comment]
I don't think it was ever fixed in the rich editor?
