### ISSUE TITLE
Notification throws 500 error on admin panel

### ISSUE THREAD

**Issue by ariaieboy** [filamentphp/filament#3704]
### Package

filament/notifications

### Package Version

v2.15.28

### Laravel Version

v9.26.1

### Livewire Version

v2.10.6

### PHP Version

8.1.9

### Problem description

In the filament admin panel when I save a new record or save an edited record the page will show me the saved notification for less than a second and after that, this error appears on my screen.
![image](https://user-images.githubusercontent.com/15873972/187020723-e666504d-5e4b-4cbd-abd9-a39229ab5586.png)

### Expected behavior

it must show the notification and not throw an error.

### Steps to reproduce

1. clone this repo: https://github.com/ariaieboy/filament-notification-bug-example
2. copy `.env.example` file to `.env`
3. create an SQLite database and set it on `.env` file
4. run migration
5. create filament user
6. login to the admin panel
7. try to create or edit a user

### Reproduction repository

https://github.com/ariaieboy/filament-notification-bug-example

**Comment by zepfietje** [comment]
I can't reproduce this issue in a fresh Laravel + Filament app.

However, I do get the exception in your reproduction repository.
It seems that somehow the `notificationClosed` Livewire event gets emitted right away when the notification is shown. Also, it passes `null` as the `id`.

Still no idea why this only occurs in some projects, but I'll dive in deeper.

**Comment by zepfietje** [comment]
Inside `notification.js` the `notification.duration` is `undefined`, which leads to the `close()` method being called right away instead of after a timeout.

**Comment by ariaieboy** [comment]
> I can't reproduce this issue in a fresh Laravel + Filament app.
> 
> However, I do get the exception in your reproduction repository. It seems that somehow the `notificationClosed` Livewire event gets emitted right away when the notification is shown. Also, it passes `null` as the `id`.
> 
> Still no idea why this only occurs in some projects, but I'll dive in deeper.

Yes, I tried the fresh install and it's ok. 
I have a project in development that has this problem and the repo that I published is a small fork from that project. 

the `notification.duration` is `undefined` but that's one problem. the other problem is that it send 2 `notificationClosed` event and because we only have 1 notification the second request will send `null` as `id` and it will throw 500 error.

i managed to fix 500 error by changing this file :https://github.com/filamentphp/filament/blob/3bf278ac19f188102b8e234c6adf97b989cd3acb/packages/notifications/src/Http/Livewire/Notifications.php#L37 
```php
    public function removeNotification(?string $id= null): void
    {
        if($id)
            $this->notifications->forget($id);
    }
```

but the actual problem is that the duration is not set correctly and it sends 2 events instead of 1.

![image](https://user-images.githubusercontent.com/15873972/187045164-f598765c-b393-4f11-9677-c53d23d9779c.png)
it's my session that shows the duration of 6000. and it contains 1 notification

**Comment by awcodes** [comment]
Livewire is being required by the root composer package and is locked at 2.10.6. Remove that from you root composer.json file then run composer update.

**Comment by danharrin** [comment]
Is this really a Livewire issue, wow

**Comment by awcodes** [comment]
Probably because it was two different versions. I didn’t test it but my hunch is that if they were on the same version this wouldn’t have been an issue.  Or there’s a bug in the @js directive with the version of livewire this example was locked to.

**Comment by ariaieboy** [comment]
thanks, @awcodes I've updated the livewire and the problem is solved. 

I think @danharrin should lock the minimum livewire version to 2.10.7 in filament composer. 

I am going to close this issue.

**Comment by zepfietje** [comment]
> thanks, @awcodes I've updated the livewire and the problem is solved.
> 
> I think @danharrin should lock the minimum livewire version to 2.10.7 in filament composer.
> 
> I am going to close this issue.

I think changing the required Livewire version for Filament would be kind of a breaking change, right?

**Comment by zepfietje** [comment]
> Probably because it was two different versions. I didn’t test it but my hunch is that if they were on the same version this wouldn’t have been an issue. Or there’s a bug in the @js directive with the version of livewire this example was locked to.

Yeah so this issue is caused by `@js`.

Recently, a fix was merged into Livewire to use the `@js` directive from Laravel instead of the one provided by Livewire if it's available in the user's Laravel version: https://github.com/livewire/livewire/pull/4876.

Previously, `@js` wouldn't work in some places and we had to use `{{ Js::from() }}` instead.
After that PR got merged, I updated the Filament notifications code to use the Blade directive instead of `{{ Js::from() }}`.

So anyone who's using a Livewire version that predates the Livewire bug fix, will run into this Filament notifications issue.
Reverting the following inside the notifications package fixes the issue:
```diff
- x-data="notificationComponent({ notification: @js($notification) })"
+ x-data="notificationComponent({ notification: {{ \Illuminate\Support\Js::from($notification) }} })"
```

@danharrin and @awcodes, do you think we should revert the `@js` change and use `{{ Js::from() }}` instead to be sure no one runs into issues like this one?
Hard to test all usages of `@js` inside Filament and prevent any issues in the future.
Personally, I'd say it was a bug in Livewire that has been fixed and users should just make sure to upgrade their Livewire version to include the bug fix.

Let me know your thoughts!

**Comment by awcodes** [comment]
Personally I would do it as Js:from() since v3 is so close and people will have to update their livewire anyway.

**Comment by awcodes** [comment]
Seems really weird that this was a patch release in livewire though.

**Comment by zepfietje** [comment]
> Personally I would do it as Js:from() since v3 is so close and people will have to update their livewire anyway.

Fair enough, will do a quick PR.

@danharrin, could you add to our v3 roadmap that we should migrate `{{ Js::from() }}` to `@js()` where possible?

**Comment by danharrin** [comment]
I don't see why we would ever need to use `Js::from()` if we just bump the Livewire version?

**Comment by zepfietje** [comment]
> I don't see why we would ever need to use `Js::from()` if we just bump the Livewire version?

Wouldn't that result in issue with existing installs where people have pinned their Livewire version?

**Comment by danharrin** [comment]
I'm sorry, but we really can't protect people who choose to do that. It's gonna cause other issues apart from this one.

**Comment by zepfietje** [comment]
Agree, I'd say bump the Livewire version.

**Comment by danharrin** [comment]
Can you fix that in your PR then? Please bump the version inside each package `composer.json`, not just the main `composer.json`

**Comment by zepfietje** [comment]
Done! https://github.com/filamentphp/filament/pull/3714

**Comment by alejandrotrevi** [comment]
omg i just wasted 2 hours of my life, shoul've searched here first 😭
