### ISSUE TITLE
Filament does not discover resources since version 2.15.16

### ISSUE THREAD

**Issue by luilliarcec** [filamentphp/filament#3713]
### Package

filament/filament

### Package Version

v2.15.28

### Laravel Version

v9.26.1

### PHP Version

PHP 8.1

### Problem description

Resources disappeared from my panel.

### Expected behavior

What did you expect to happen instead?

### Steps to reproduce

Well, I had my resources previously created from version 2.14.* and when I did composer update to the latest version, my resources disappeared from the panel, but what is really happening is that Filament::getResources() is not getting them for me. It's weird but I did tests and this happens from version 2.15.16 onwards.

### Reproduction repository

https://github.com/luilliarcec/filament-bug-2.15.16

**Comment by danharrin** [comment]
Reopening, our bot only checks GitHub repositories at this time

**Comment by luilliarcec** [comment]
Moving `Filament::registerUserMenuItems()` to the `boot` method instead of `register` fixed the problems.

**Comment by danharrin** [comment]
Cool, please make sure that you only bind to the Laravel container in `register()`, as per Laravel guidelines

https://laravel.com/docs/9.x/providers#the-register-method
