### ISSUE TITLE
User dropdown does not close anymore

### ISSUE THREAD

**Issue by ksassnowski** [filamentphp/filament#3769]
### Package

filament/filament

### Package Version

v2.15.34

### Laravel Version

v9.27.0

### PHP Version

8.1

### Problem description

The 2.15.34 release of Filament introduced a visual bug that causes the user menu dropdown in the admin panel to always be open. Clicking on the user avatar positions the dropdown correctly, but you're still unable to close it. This is probably related to #3443 but I haven't looked very deep into it. Version `2.15.33` does not contain this bug.

![CleanShot 2022-08-31 at 07 31 43@2x](https://user-images.githubusercontent.com/5139098/187599666-a10463e7-7a10-4f67-84b5-30e734f63a00.png)

### Expected behavior

The dropdown should be closed by default and it should be possible to close it again after opening it.

### Steps to reproduce

1. Install `filament/filament:2.15.34` in a fresh application
2. Log in with any user
3. Notice that the user dropdown is already open and off to the side
4. Clicking on the user avatar does not close the dropdown

### Reproduction repository

https://github.com/ksassnowski/filament-user-dropdown-bug

**Comment by mohameedsherif** [comment]
Same issue here

**Comment by invaders-xx** [comment]
There's a discussion opened on Discord and it's a known issue. Please revert to 2.15.33 until issue solved by maintainers

**Comment by danharrin** [comment]
We are very sorry for the inconvenience here. I just released a new version.

I pulled down PR #3443, checked it out locally, and it was all fine. Then for some reason it was broken when it got released. Maybe there was some cache in my dummy app that was still showing me the old version or something.

Should all be sorted now, we will investigate what happened.
