### ISSUE TITLE
Support for Spatie translation plugin in Modals

### ISSUE THREAD

**Issue by mahfoudfx** [filamentphp/filament#3772]
### Package

filament/filament

### Package Version

v2.15.33

### Laravel Version

v9.27.0

### Livewire Version

v2.10.7

### PHP Version

PHP 8.1.9

### Problem description

Using Spatie Translation Plugin, Filament Admin is not able to show data correctly in modals, even for edit/view. The create insert data correctly with used locale.

Modal View
![image](https://user-images.githubusercontent.com/31103481/187618666-e260ac48-8afe-4ce2-b2d0-b53b163ffdce.png)

Modal Edit
![image](https://user-images.githubusercontent.com/31103481/187618830-044f7a10-8f1e-4726-9849-51cd715eacca.png)

### Expected behavior

Displaying data correctly as in classic form.

### Steps to reproduce

Try to insert data (if you'll use my repo, you can try in Items Category Names).

### Reproduction repository

https://github.com/mahfoudfx/filamentdev

**Comment by danharrin** [comment]
Hey, this is not an issue, we just haven't added support for this at the current time. From what I understand, Livewire v3 will make this feature possible.

**Comment by mahfoudfx** [comment]
> Hey, this is not an issue, we just haven't added support for this at the current time. From what I understand, Livewire v3 will make this feature possible.

Sorry, I didn't found any mention of this detail, or maybe I missed it.
BTW, is it possible to have a workaround for example for `Edit action` using [Lifecycle hooks](https://filamentphp.com/docs/2.x/admin/resources/listing-records#lifecycle-hooks-1), with the method `beforeFormFilled()` ?

```php
use Filament\Tables\Actions\EditAction;
 
EditAction::make()
    ->beforeFormFilled(function () {
        // Runs before the form fields are populated from the database.
    })
```

**Comment by danharrin** [comment]
> BTW, is it possible to have a workaround for example for Edit action using [Lifecycle hooks](https://filamentphp.com/docs/2.x/admin/resources/listing-records#lifecycle-hooks-1), with the method beforeFormFilled() ?

Whats the use case?

**Comment by mahfoudfx** [comment]
To display the translation in Edit modal, using [Spatie Translatable](https://spatie.be/docs/laravel-translatable/v6/basic-usage/getting-and-settings-translations#content-getting-a-translation). Something like :

```php
EditAction::make()
    ->beforeFormFilled(function () {
        return $query->name->getTranslations('hello', app()->getLocale(), true);
    })
```

**Comment by mahfoudfx** [comment]
``> > BTW, is it possible to have a workaround for example for Edit action using [Lifecycle hooks](https://filamentphp.com/docs/2.x/admin/resources/listing-records#lifecycle-hooks-1), with the method beforeFormFilled() ?
> 
> Whats the use case?

I think that I found the cleanest workaround using [Field lifecycle Hydration](https://filamentphp.com/docs/2.x/forms/advanced#hydration) which will display the correct translation on both `View` & `Edit` `Modal` and allow the `Create` action.
If you will agree, I can add it to the Filament [Tricks](https://filamentphp.com/tricks) section for poeple who are using the translatable package and dealing with the same issue awaiting for a core solution.
```php
return $form
            ->schema([
                TextInput::make('name')
                    ->afterStateHydrated(function (TextInput $component, $state) {
                        !($state) ?: $component->state($state[app()->getLocale()]);
                    }),
                TextInput::make('description'),
            ]);
```
This will give the below display.
![image](https://user-images.githubusercontent.com/31103481/188949187-152e4acd-04a7-4663-9515-9e26764a788a.png)

However, I noticed abnormal behaviour. Excluding the `Create` action, the following combinations will fire a `Console` warnings and errors without disturbing the operability of Filament, also data is filled and read correctly.

- `View` different entries (starting from the second view click).
- `Edit` different entries (starting from the second edit click).
- `View` followed by `Edit` or the reverse: `Edit` followed by `View` of the same or different table entries.

You can check below the fired errors.
![image](https://user-images.githubusercontent.com/31103481/188956204-d3ff02da-73c9-4cd0-8e8b-6c0c3289f623.png)

![image](https://user-images.githubusercontent.com/31103481/188956340-e6683095-9778-4193-8bb2-189addc18209.png)

**Comment by francoism90** [comment]
Any news on this?

**Comment by mahfoudfx** [comment]
It seems to not be supported using Livewire V2, maybe available with the next V3.
Awaiting for an official support, I have written a [Workaround to display Spatie Translation on Modals](https://filamentphp.com/tricks/workaround-to-display-spatie-translation-on-modals) that you can find on the Tricks section on the filamentphp website.

**Comment by francoism90** [comment]
@mahfoudfx Thanks for sharing your solution. :)

Unfortunately this doesn't work when a user switches to a locale using the switcher action. It always uses the (current) app locale (not model), right?

I was thinking of using something like a keyValue or even a repeater instead. But it would be great if it could be included as Livewire V3 will take a long time to be completed.

**Comment by mahfoudfx** [comment]
@francoism90 I think that you can customize the condition according to your usecase.
The most important thing in this workaround is the use of the [Field lifecycle Hydration](https://filamentphp.com/docs/2.x/forms/advanced#hydration) advanced feature of filament.

**Comment by francoism90** [comment]
@mahfoudfx Thanks, I'm new to Filament, it would be great if it could get the locale from the parent.

**Comment by Schrolli91** [comment]
Is this now possible, to use the translatable package on modals?
With the trick from @mahfoudfx i can show and edit the data - but i want also a localeswitcher to add another language data to the record.
