### ISSUE TITLE
Toggle Column drop take full width

### ISSUE THREAD

**Issue by aymanalareqi** [filamentphp/filament#3793]
### Package

filament/tables

### Package Version

v2.15.38

### Laravel Version

v9.27.0

### Livewire Version

v2.3

### PHP Version

PHP 8.1.4

### Problem description

when I open toggle column drop down it opened in full width like this
![ToggleIssue](https://user-images.githubusercontent.com/77433449/187770764-4400f53b-1c86-4a3a-972f-88445e251b46.PNG)

### Expected behavior

toggle column drop down opened in small with like this
![Toggle solution](https://user-images.githubusercontent.com/77433449/187771167-dacc1c6a-2052-45e0-b813-7e568d0f4767.PNG)

### Steps to reproduce

make some table toggleable then open toggle column drop down

### Reproduction repository

https://github.com/filamentphp/filament

**Comment by danharrin** [comment]
Please run `artisan filament:upgrade`, delete any published views, and recompile your theme.
