### ISSUE TITLE
Generate Resource - Toggle has MaxLength Error

### ISSUE THREAD

**Issue by lucidpolygon** [filamentphp/filament#3807]
### Package

filament/filament

### Package Version

2.0

### Laravel Version

9.19

### Livewire Version

2.1

### PHP Version

8.0.2

### Problem description

- If a model has a boolean field and you generate a resource
- The boolean filed throws attached error
<img width="1281" alt="Screen Shot 2022-09-01 at 10 42 26 AM" src="https://user-images.githubusercontent.com/40432572/187958856-5c554117-756f-435d-9309-d2f58e29fe2b.png">

### Expected behavior

- The solution boolean field does not need maLength

### Steps to reproduce

Go to admin > customers > create

### Reproduction repository

https://github.com/lucidpolygon/filament-asda

**Comment by zepfietje** [comment]
So, if you remove the non-existent `maxLengt()` method, it all works.

**Comment by danharrin** [comment]
@zepfietje the issue is that maxLength() should only be generated for TextInput and Textarea fields.

**Comment by zepfietje** [comment]
Oh, I read the description but missed that the resource generation by Filament is the part it's all about, sorry!
