### ISSUE TITLE
Edit pivot attribute bug in v2.15.40

### ISSUE THREAD

**Issue by molcsab** [filamentphp/filament#3826]
### Package

filament/filament

### Package Version

v2.15.40

### Laravel Version

v9.27.0

### Livewire Version

v2.3

### PHP Version

PHP 8.1

### Problem description

After upgrading to v2.15.40 pivot attributes are not updating when editing a relation in RM
If downgrading to v2.15.39 there is no issue

### Expected behavior

Update notes pivot attribute

### Steps to reproduce

Edit a record in RM

### Reproduction repository

https://github.com/molcsab/pivotbug

### Relevant log output

```shell
No errors, but the query in debugbar looks like this:
update `role_user` set `notes` = 'test' where `user_id` is null and `role_id` is null
```

**Comment by zepfietje** [comment]
@molcsab, could you test if this comment fixes your issue? https://github.com/filamentphp/filament/pull/3789#issuecomment-1235511597
