### ISSUE TITLE
Unexpected table action data during test assertion

### ISSUE THREAD

**Issue by AndyTWF** [filamentphp/filament#3833]
### Package

filament/tables

### Package Version

2.15.45

### Laravel Version

9.27.0

### Livewire Version

2.10.7

### PHP Version

8.1.8

### Problem description

This is a long one so thanks in advance for looking into it!

I have a test that does the following:

```
        Livewire::test(HoldsRelationManager::class, ['ownerRecord' => $navaid])
            ->mountTableAction(ViewAction::class, $hold)
            ->assertTableActionDataSet(
                [
                    'description' => $hold->description,
                    'inbound_heading' => $hold->inbound_heading,
                    'minimum_altitude' => $hold->minimum_altitude,
                    'maximum_altitude' => $hold->maximum_altitude,
                    'turn_direction' => $hold->turn_direction,
                    'restrictions' => [
                        [
                            'type' => 'level-block',
                            'data' => [
                                'levels' => [
                                    [
                                        'level' => 1000,
                                    ],
                                    [
                                        'level' => 2000,
                                    ],
                                ],
                                'id' => $restriction->id,
                            ],
                        ],
                    ],
                ],
            );
```

The relation manager has a form which handles the restrictions  as "Blocks", as there are two different types. The relevant "block" is as follows:

```
      Forms\Components\Builder\Block::make('level-block')
          ->label(__('form.holds.level_block.label'))
          ->schema([
              Forms\Components\Repeater::make('levels')
                  ->label(__('form.holds.level_block_levels.label'))
                  ->helperText(__('form.holds.level_block_levels.helper'))
                  ->schema([
                      Forms\Components\TextInput::make('level')
                          ->integer()
                          ->step(100)
                          ->minValue(1000)
                          ->maxValue(60000)
                          ->required(),
                  ]),
          ]),
```

The ViewAction on the table has a `mutateRecordDataUsing` callback, which mutates the record data to end up like the following:

```
        $data['restrictions'] = $record->restrictions->map(
            fn (HoldRestriction $restriction) => match ($restriction->restriction['type']) {
                'minimum-level' => [
                    'type' => $restriction->restriction['type'],
                    'data' => [
                        ...$restriction->restriction,
                        'id' => $restriction->id,
                        'runway' => [
                            'designator' => isset($restriction->restriction['runway']) ? $restriction->restriction['runway']['designator'] : null,
                        ],
                    ],
                ],
                'level-block' => [
                    'type' => $restriction->restriction['type'],
                    'data' => [
                        'id' => $restriction->id,
                        'levels' => collect($restriction->restriction['levels'])
                            ->map(fn (int $level) => ['level' => $level])
                            ->toArray(),
                    ],
                ]
            }
        )->toArray();
```

Since the past week or so, this test, which was passing before, has started failing. The reason is because whilst the above code that mutates the record data would return an array of items looking a bit like this:

```
array:8 [
  "id" => 4
  "navaid_id" => 4
  "inbound_heading" => 210
  "minimum_altitude" => 17146
  "maximum_altitude" => 11109
  "turn_direction" => "left"
  "description" => "impedit"
  "restrictions" => array:1 [
    0 => array:2 [
      "type" => "level-block"
      "data" => array:2 [
        "id" => 2
        "levels" => array:2 [
          0 => array:1 [
            "level" => 1000
          ]
          1 => array:1 [
            "level" => 2000
          ]
        ]
      ]
    ]
  ]
]
```

When the test asserts against the mountedTableActionData, the data looks like this:

```
array:8 [
  "id" => 4
  "navaid_id" => 4
  "inbound_heading" => 210
  "minimum_altitude" => 17146
  "maximum_altitude" => 11109
  "turn_direction" => "left"
  "description" => "impedit"
  "restrictions" => array:1 [
    1 => array:2 [
      "type" => "level-block"
      "data" => array:2 [
        "id" => 2
        "levels" => array:1 [
          0 => array:1 [
            "level" => 2000
          ]
        ]
      ]
    ]
  ]
]
```

As you can see, it looks like some data has gotten lost. Namely the original 0 index of the "levels" array, which contained the value `1000` has gone. The "restrictions" array is also keyed at 1 now, rather than an array of objects, as it was previously.

The behaviour does not happen when using Filament through the front-end - and everything appears in the form just how you'd expect (including multiple levels in the repeater).

I can't pintpoint an exact version where it stopped working, sorry! But definitely in the last week or so.

### Expected behavior

I would expect the data structure to be same as the test assertion - as was working previously.

### Steps to reproduce

Not entirely sure - but I would probably say a Repeater field and a `mutateRecordDataUsing` callback at the very least.

### Reproduction repository

https://github.com/VATSIM-UK/uk-controller-api

**Comment by AndyTWF** [comment]
Done some further digging here - looks like the break occurs in v2.15.19 :)

**Comment by AndyTWF** [comment]
So I figured out why this has happened - in the test I used `Str::createUuidsUsingSequence` in order to make the UUID generation deterministic, which then allows me to call `assertTableActionDataSet` with set results.

Looks like something in 2.15.19 changed the order in which the state gets populated, so fields in the repeater were having their UUIDs generated in a different order :)

**Comment by danharrin** [comment]
Nice, glad you got it working. You are right, the array keys are just internal and don't really need testing, just the content.
