### ISSUE TITLE
DatePicker doesn't work when using dot/array notation

### ISSUE THREAD

**Issue by PhiloNL** [filamentphp/filament#3845]
### Package

filament/forms

### Package Version

v2.15.43

### Laravel Version

v9.27.0

### Livewire Version

v2.10.7

### PHP Version

PHP 8.1

### Problem description

When using the datepicker in combination with the dot/array notation, the state doesn't seem to apply.

```
DatePicker::make('foobar.startDate')->label(__('Start date')) // This will always be `null`
```

- `foobar.startDate` will be null
- `topLevelDate` will be the date you have chosen

https://github.com/PhiloNL/filament-form-datepicker-bug/blob/main/app/Http/Livewire/Form.php

### Expected behavior

The datepicker value should be set on the nested array key.

### Steps to reproduce

- Install the repository
- Use the date picker to select a date
- Click the submit button to see the response.

### Reproduction repository

https://github.com/PhiloNL/filament-form-datepicker-bug

**Comment by danharrin** [comment]
Make sure you always call `$this->form->fill()` for every single form, on `mount()`, as per the docs. That method does a lot of initialisation work and ensures nested array keys exist.

**Comment by PhiloNL** [comment]
✅ Thanks!
