### ISSUE TITLE
Route [filament.resources.testimonials.index] not defined

### ISSUE THREAD

**Issue by PirellYO** [filamentphp/filament#3860]
### Package

filament/filament

### Package Version

v2.0.0

### Laravel Version

v9.x

### Livewire Version

v8.0.0

### PHP Version

PHP.8.x

### Problem description

![image](https://user-images.githubusercontent.com/43124677/188335834-a3db5586-1254-4c8d-b78d-a07e0e578609.png)

I get this error when creating Resources

`php artisan make:filament-resource CategoryResource`

### Expected behavior

Successfully created CategoryResource!

Acces admin panel

### Steps to reproduce

creating resource

### Reproduction repository

none

**Comment by gintoki05** [comment]
i need the answer T_T
