### ISSUE TITLE
Table widget is returning empty result set when "All" is selected in pagination 

### ISSUE THREAD

**Issue by molcsab** [filamentphp/filament#3893]
### Package

filament/filament

### Package Version

v2.15.45

### Laravel Version

v9.27.0

### Livewire Version

v2.10.7

### PHP Version

PHP v8.1.3

### Problem description

When "All" option is selected in the pagination for table widgets, no results are displayed.

The unerlying query from Debugbar is like:

`select * from `table` ...  limit 0 offset 0`

### Expected behavior

I shold display all the results

### Steps to reproduce

Go to [Filament demo](https://demo.filamentphp.com/) and on the dashboard select "All" in the "Latest orders" widget

### Reproduction repository

https://github.com/filamentphp/demo

**Comment by Sicklou** [comment]
I found the bug today as well.

@danharrin I found that passing `null` instead of `-1` make it works. If this could help you.

**Comment by zepfietje** [comment]
This should have been fixed by https://github.com/filamentphp/filament/pull/3864.

Note that the Filament demo currently runs on `v2.15.44`, which is not the latest version (v2.15.45).

Are you sure you're experiencing the issue in the latest version of Filament in your project?

**Comment by Sicklou** [comment]
Oops sorry.
For me, it is when using the simplePaginate with the Table Component as a standalone.

So I guess, we need to change the documentation : https://filamentphp.com/docs/2.x/tables/getting-started#simple-pagination

I made a PR : https://github.com/filamentphp/filament/pull/3898

**Comment by molcsab** [comment]
@zepfietje It is fixed in v2.15.45. Before reporting the error I issued a composer update command and no new filament package was installed, so the version was v2.15.44.
