### ISSUE TITLE
RelationManager breaking form values when edit

### ISSUE THREAD

**Issue by joaovdiasb** [filamentphp/filament#3906]
### Package

filament/tables

### Package Version

v2.15.45

### Laravel Version

v9.28.0

### Livewire Version

v2.10.7

### PHP Version

PHP 8.1.9

### Problem description

In RelationManager when view some record with RichEditor before edit, throws a error in console and don't show the form values.

<img width="617" alt="CleanShot 2022-09-08 at 09 30 47@2x" src="https://user-images.githubusercontent.com/51106311/189122320-bbdfb3ed-121e-4381-83c1-4f719a3f33fc.png">

### Expected behavior

Show form values

### Steps to reproduce

1 - Add in RelationManager form the RichEditor
```php
RichEditor::make()
```
2 - View some RelationManager record with ViewAction
```php 
Tables\Actions\ViewAction::make() 
```
3 - Edit some RelationManager record with EditAction
```php 
Tables\Actions\EditAction::make()
```

### Reproduction repository

https://github.com/joaovdiasb/fillament-process

**Comment by zepfietje** [comment]
I can't reproduce the issue.

Could you add a seeder and clear steps to reproduce the problem using your reproduction repository?

**Comment by joaovdiasb** [comment]
Video of reproduction https://drive.google.com/file/d/15Sf1EZagEBxkIO2927sa3jlzM461wmyz/view?usp=sharing

already have the data in factory
php artisan migrate:fresh --seed

**Comment by nunoxavier** [comment]
@zepfietje I'm currently having similar issues (not entirely related to the RichEditor), you can reproduce it on the current Filament demo 
[https://demo.filamentphp.com/shop/brands/20/edit?activeRelationManager=0](https://demo.filamentphp.com/shop/brands/20/edit?activeRelationManager=0)

Steps:
1. click on one item from the products list, then click outside the modal
2. click on another item from the products list, you'll see the console error

Thanks in advance

Edit: worth to mention that by submitting the modal's form and then opening a different item will not produce any error

**Comment by joaovdiasb** [comment]
> @zepfietje I'm currently having similar issues (not entirely related to the RichEditor), you can reproduce it on the current Filament demo https://demo.filamentphp.com/shop/brands/20/edit?activeRelationManager=0
> 
> Steps:
> 
> 1. click on one item from the products list, then click outside the modal
> 2. click on another item from the products list, you'll see the console error
> 
> Thanks in advance
> 
> Edit: worth to mention that by submitting the modal's form and then opening a different item will not produce any error

Yes, I've had this problem with Select too, outside the relation manager, normal table.

**Comment by danharrin** [comment]
Does #4764 fix this?

**Comment by joaovdiasb** [comment]
> Does #4764 fix this?

still not for what i'm doing

Steps:
1. View some relation manager
2. Close
3. Edit another

**Comment by danharrin** [comment]
Please check again in the latest release

**Comment by joaovdiasb** [comment]
Its fixed now, thanks!

> Please check again in the latest release
