### ISSUE TITLE
Compatibility with blade-ui-kit/blade-heroicons 2.*

### ISSUE THREAD

**Issue by nocodelab** [filamentphp/filament#3916]
### Package

filament/notifications

### Package Version

2.0

### Laravel Version

9.28.0

### Livewire Version

2.10.7

### PHP Version

8.1

### Problem description

The dependency to blade-ui-kit/blade-heroicons should be updated to 2.* to support the new heroicons version (2).

### Expected behavior

The installation should complete succesfully.

### Steps to reproduce

composer require blade-ui-kit/blade-heroicons:"^2.0"
composer require filament/notifications:"^2.0"

### Reproduction repository

https://github.com/blade-ui-kit/blade-heroicons

### Relevant log output

```shell
Problem 1
    - filament/notifications[v2.15.1, ..., 2.x-dev] require blade-ui-kit/blade-heroicons ^1.2 -> found blade-ui-kit/blade-heroicons[1.2.0, 1.2.1, 1.3.0, 1.3.1] but it conflicts with your root composer.json require (^2.0).
    - Root composer.json requires filament/notifications ^2.0 -> satisfiable by filament/notifications[v2.15.1, ..., 2.x-dev].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.
```

**Comment by ryangjchandler** [comment]
@nocodelab This won't have until version 3.x of Filament because it's considered a breaking change for existing applications using renamed / removed icons in the new version of Heroicons.

**Comment by zepfietje** [comment]
Additionally, we can't upgrade to v2 of the Blade Heroicons package, since it dropped support for Laravel 8.

Closing this issue, as it's already being tracked on our v3 roadmap: https://github.com/orgs/filamentphp/projects/2/views/1.

**Comment by danharrin** [comment]
Reopening this so people stop asking

**Comment by zepfietje** [comment]
Done for v3: https://github.com/filamentphp/filament/issues/4490.
