### ISSUE TITLE
TernaryFilter indicators showing as "Yes" or "No" by default and no `->indicator()` changes the displayed text 

### ISSUE THREAD

**Issue by belzaaron** [filamentphp/filament#3922]
### Package

filament/tables

### Package Version

v2.15.45

### Laravel Version

v9.28.0

### Livewire Version

v2.10.7

### PHP Version

v8.1.8

### Problem description

Creating a `TernaryFilter` for a table as such:
```php
TernaryFilter::make('email')->label('Has Email')->nullable()
```
or
```php
TernaryFilter::make('email')->label('Has Email')->indicator('Has Email')->nullable()
```
Will result in the "Active filters" indicator to be "Yes" or "No" respectively:
![Example of Active filters text](https://i.imgur.com/B5ePXVv.png)

As you could imagine some TernaryFilters can really be as simple as "Yes" or "No" for their values (which is default), and regarding their "Active filter" labels being the same this can be quite confusing:
![confusing Active filter indicators](https://i.imgur.com/9kvATCb.png)

### Expected behavior

As per the documentation I would expect "Has Email: Yes" or "Has Email: No", considering the [documentation](https://filamentphp.com/docs/2.x/tables/filters#active-indicators) and the `->label()`/`->indicator()` I've set.

### Steps to reproduce

Create a simple TernaryFilter without using something to the effect of `->trueLabel('Has Email')->falseLabel('Has No Email')`.

**Comment by danharrin** [comment]
Fixed by #3931
