### ISSUE TITLE
Admin: Database notification trigger misaligned below sm width

### ISSUE THREAD

**Issue by kamilst96** [filamentphp/filament#3940]
### Package

filament/filament

### Package Version

v2.16.1

### Laravel Version

v9.x

### Livewire Version

v2.10.x

### PHP Version

PHP 8.1.9

### Problem description

Notification trigger becomes misaligned on mobile.

![Zrzut ekranu z 2022-09-10 17-44-33](https://user-images.githubusercontent.com/37311362/189490995-afc2694c-c9f4-4f5b-acbb-0337521f0420.png)

![Zrzut ekranu z 2022-09-10 17-44-38](https://user-images.githubusercontent.com/37311362/189490999-365b969d-b000-4ac9-99c7-1bc2323045b0.png)

### Expected behavior

Keep vertical margins.

### Steps to reproduce

Enable database notifications on any standard filament admin deployment.

### Reproduction repository

https://github.com/kamilst96/filament-issue-repo

**Comment by danharrin** [comment]
Can you submit a PR to fix this?

**Comment by kamilst96** [comment]
Yeah, sorry about that. I failed to locate the issue on my first attempt.
