### ISSUE TITLE
How to access the current record in table actions

### ISSUE THREAD

**Issue by Xoshbin** [filamentphp/filament#3962]
### Package

filament/tables

### Package Version

2.0

### Laravel Version

v9

### Livewire Version

2.5

### PHP Version

PHP 8.1

### Problem description

How can I access the current record in actions please?

```
protected function getTableQuery(): Builder
    {
        return Auth::user()->followers()->getQuery();
    }
protected function getTableActions(): array
    {
        return [
            Action::make('unfollow')
                ->action(fn(Followable $record) => $this->unfollow($record)),
        ];
    }
public function unfollow($record)
    {
        Auth::user()->unfollow($record);
    }
```
it gives this error:

> App\Http\Livewire\Dashboard\Followers::App\Http\Livewire\Dashboard{closure}(): Argument https://github.com/filamentphp/filament/pull/1 ($record) must be of type Overtrue\LaravelFollow\Followable, null given, called in /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php on line 36

### Expected behavior

It should produce a record, but the record is null

### Steps to reproduce

Clone the repo
seed the database
login with one of the generated users
go to /followers page

### Reproduction repository

https://github.com/Xoshbin/filament-action-record

**Comment by Xoshbin** [comment]
> This is not an issue. Anyway you can do this (remove model typehint)
> 
> ```
> protected function getTableActions(): array
> {
>     return [
>         Action::make('unfollow')
>             ->action(fn($record) => $this->unfollow($record)),
>     ];
> }
> ```

I tested that too, it's still null.
You can even test inside the function like that it's still null
Action::make('unfollow')
            ->action(function($record){
            dd($record);
        }
),

**Comment by titantwentyone** [comment]
Your query implies that you are displaying a list of users followers. It is probably the case that you cannot unfollow someone that follows you. Only the follower can unfollow. The query should be something like this:

```
protected function getTableQuery(): Builder
{
    return Auth::user()->followings()->getQuery();
}
```

and your columns should be:

```
protected function getTableColumns(): array
{
    return [
        Tables\Columns\TextColumn::make('followable.name'),
    ];
}
```
Hopefully I've understood what you're aiming for.

**Comment by Xoshbin** [comment]
> Your query implies that you are displaying a list of users followers. It is probably the case that you cannot unfollow someone that follows you. Only the follower can unfollow. The query should be something like this:
> 
> ```
> protected function getTableQuery(): Builder
> {
>     return Auth::user()->followings()->getQuery();
> }
> ```
> 
> and your columns should be:
> 
> ```
> protected function getTableColumns(): array
> {
>     return [
>         Tables\Columns\TextColumn::make('followable.name'),
>     ];
> }
> ```
> 
> Hopefully I've understood what you're aiming for.

OMG 🤦‍♂️, I feel very bad.
Thank you
