### ISSUE TITLE
Default values not working

### ISSUE THREAD

**Issue by YaminMECHQI** [filamentphp/filament#4039]
### Package

filament/forms

### Package Version

v2

### Laravel Version

v9

### Livewire Version

v2

### PHP Version

php 8

### Problem description

the default value not working on resource

### Expected behavior

set the default values

### Steps to reproduce

                            Toggle::make('is_published')
                             ->default(true),

                            Radio::make('productType')
                            ->options([
                                'simple' => 'Simple',
                                'simple_variation' => 'Simple variation',
                                'double_variation' => 'Double variation'
                                ])
                                ->descriptions([
                                    'simple' => 'Without variation.',
                                    'simple_variation' => 'Ex: S, M, L.',
                                    'double_variation' => 'Ex: S [Blue, Red], M [White, Black].'
                                ])
                                ->reactive()
                                ->default('simple')
                                ->afterStateUpdated(function (Closure $set, Closure $get) {
                                    dd((string) $get('productType'));
                                    $set('variants', null);
                                }),

### Reproduction repository

https://github.com/YaminMECHQI/yourshop-admin

**Comment by danharrin** [comment]
The repository is giving me a 404, please make it public

**Comment by pxlrbt** [comment]
@danharrin  Considering this line `$set('variants', null);` I think there's confusion that defaults only work while loading the Create Page.

**Comment by danharrin** [comment]
Yes. I assume thats the problem here.

@YaminMECHQI, defaults are only filled on the Create page, not Edit. Otherwise we would be overwriting your data.

Please fix the repo or provide better demo code, as the code you pasted works on my end.
