### ISSUE TITLE
[Forms\Components\FileUpload] Every time I edit a record, the file redownload 

### ISSUE THREAD

**Issue by xuchunyang** [filamentphp/filament#4088]
### Package

filament/forms

### Package Version

v2.16.5

### Laravel Version

v9.30.1

### Livewire Version

v2.10.7

### PHP Version

8.1.7

### Problem description

I use the FileUpload field to upload file which works fine. However, every time I edit the record, the already uploaded file gets redownloaded. In the screenshot, when I try to edit the record, the file gets downloaded via fetch automatically:

<img width="1745" alt="截屏2022-09-19 06 13 44" src="https://user-images.githubusercontent.com/4550353/190930162-307a7bf4-a415-4fe5-bb21-40db11ad42a1.png">

I understand this is fine for images, since redownload the whole file is needed to preview them. 

However, for non-image files, this is not acceptable, e.g., if I add 10 PDF files, each one is 2MB, then every time before I can edit the record, the browser will download 20MB data.

### Expected behavior

The FileUpload field should not download files each time I edit the record.

### Steps to reproduce

1. Create a model such as Post, with `attachment` column to store file path.
2. Create PostResource with `Forms\Components\FileUpload::make('attachment')` to edit the field
3. Goto http://127.0.0.1:8000/admin/posts/create to create a new Post by uploading a PDF attachment (non-image)
4. Goto http://127.0.0.1:8000/admin/posts/1/edit

### Reproduction repository

https://github.com/xuchunyang/filament-FileUpload-redownload-issue

**Comment by danharrin** [comment]
Notes:

https://pqina.nl/filepond/docs/api/instance/properties/#files
https://github.com/filamentphp/filament/blob/d10b3ee3cb4015be6574b5835f8e9ca23e1449a1/packages/forms/resources/js/components/file-upload.js#L298-L303

**Comment by danharrin** [comment]
Moved from v2 to v3, since it would be easiest to implement if we could change the `getUploadedFileUrls()` to `getUploadedFiles()` and return the URLs, and metadata like size & potentially file name if they're stored in a separate column

**Comment by danharrin** [comment]
This has now been fixed in v3, but only for non-images. Images still download since they get previewed.

**Comment by sadegh19b** [comment]
> This has now been fixed in v3, but only for non-images. Images still download since they get previewed.

@danharrin Can fixed this bug for v2 please? i use the filament for my new project and have this bug for pdf files.

Thank you

**Comment by danharrin** [comment]
Its not really a bug, just an inconvenience that files download to calculate their size. PDF files are still uploadable through Filament in v2. The fix required a breaking change.

**Comment by sadegh19b** [comment]
> Its not really a bug, just an inconvenience that files download to calculate their size. PDF files are still uploadable through Filament in v2. The fix required a breaking change.

@danharrin I think it's a bug, for me it's infinite loading in edit page and cannot upload a new file ! (it's happening only for pdf)

**Comment by danharrin** [comment]
okay well the issue you commented on isnt the same one then.

check https://filamentphp.com/tricks/file-upload-previews-not-loading

**Comment by MaiwandZazai786** [comment]
how can i display a pdf/file  that i have already uploaded in the edit page?

**Comment by danharrin** [comment]
The PDF plugin for Filepond is currently incredibly buggy and we cannot use it

**Comment by pingumen96** [comment]
Hello, it's problematic to load a large file (>1GB) into Filepond because, as it currently functions, the file must be downloaded before the download button becomes operational.

The following is my form field declaration:
```

FileUpload::make('files')->label($form->getOperation() == 'create' ? 'Carica file' : 'Scarica file')
                                ->disk('s3')
                                ->directory('doc_files')->storeFileNamesIn('files')
                                ->required()->visibility('private')->fetchFileInformation(false)
                                ->openable()->disabledOn('edit')->previewable(false)->extraAttributes(['class' => 'input-with-file']),
```

Even if there is fetchFileInformation(false), it always downloads the file, which is a problem

**Comment by MioukiSan** [comment]
does anyone here tried to view the file using modal in filament?
