### ISSUE TITLE
SpatieMediaLibrary retrieving signed image does not work in relationship with AWS S3

### ISSUE THREAD

**Issue by riomigal** [filamentphp/filament#4107]
### Package

filament/spatie-laravel-media-library-plugin

### Package Version

v2.0

### Laravel Version

v9.0.0

### Livewire Version

v2.0.0

### PHP Version

PHP 8.1.4

### Problem description

I already wrote this issue on discord, when trying to access an image from a RelationshipManager form it has CORS issues since it doesn't set the correct headers. It's not a problem on AWS, I can upload and retrieve the image with the exact same form on the resource.

### Expected behavior

Should retrieve image in relationship

### Steps to reproduce

Upload an image on S3 bucket (private) try to access it directly in the form of the Profile Resource, it will work. Try to access it in the ProfileRelationship in the User Resource, it won't work.

### Reproduction repository

https://bitbucket.org/rio_migal/filament-media-library-issue/src/master/

**Comment by saade** [comment]
Ralated?

https://discord.com/channels/883083792112300104/883083792653381695/1021471776888344577

https://discord.com/channels/883083792112300104/883083792653381695/1021485826099654757

**Comment by riomigal** [comment]
Is similar. I am having the issue only in the relationship form. 

Header from profile resource (Working):
+headers: Symfony\Component\HttpFoundation\HeaderBag {#48 ▼
    #headers: array:10 [▼
      "host" => array:1 [▶]
      "connection" => array:1 [▶]
      "cache-control" => array:1 [▶]
      "upgrade-insecure-requests" => array:1 [▶]
      "user-agent" => array:1 [▶]
      "accept" => array:1 [▶]
      "referer" => array:1 [▶]
      "accept-encoding" => array:1 [▶]
      "accept-language" => array:1 [▶]
      "cookie" => array:1 [▶]
    ]
    #cacheControl: array:1 [▼
      "max-age" => "0"
    ]
  }

Header from profile relationship resource (Not working: As you can see it doesn't even take over the settings of media-library config -> CacheControl... and it adds additional headers)
 +headers: Symfony\Component\HttpFoundation\HeaderBag {#48 ▼
    #headers: array:13 [▼
      "host" => array:1 [▶]
      "connection" => array:1 [▶]
      "content-length" => array:1 [▶]
      "accept" => array:1 [▶]
      "x-csrf-token" => array:1 [▶]
      "user-agent" => array:1 [▶]
      "x-livewire" => array:1 [▶]
      "content-type" => array:1 [▶]
      "origin" => array:1 [▶]
      "referer" => array:1 [▶]
      "accept-encoding" => array:1 [▶]
      "accept-language" => array:1 [▶]
      "cookie" => array:1 [▶]
    ]

**Comment by bureauvk** [comment]
I also had issues with CORS. Uploading and showing worked, but sometimes the CORS issue came up.
I configured the CORS on the Permission tab in the Bucket dashboard and no errors since.

```
[
    {
        "AllowedHeaders": [],
        "AllowedMethods": [
            "GET",
            "PUT",
            "POST",
            "DELETE",
            "HEAD"
        ],
        "AllowedOrigins": [
            "*"
        ],
        "ExposeHeaders": []
    }
]
```

Is this the way we should fix this? Happened to me on multiple S3 buckets.

**Comment by danharrin** [comment]
Yeah I can't reproduce this, and that S3 config works for my other projects
