### ISSUE TITLE
Form data is missing when entering empty string as Form Component name

### ISSUE THREAD

**Issue by pascalvgemert** [filamentphp/filament#4122]
### Package

filament/forms

### Package Version

v2.16.7

### Laravel Version

v9.31.0

### Livewire Version

v2.10.7

### PHP Version

PHP 8.1.5

### Problem description

When I build the following Form Schema for a resource:

```
public static function form(Form $form): Form
{
    return $form
        ->schema([
            Forms\Components\TextInput::make('first_name')->required(),
            Forms\Components\Placeholder::make(''),
            Forms\Components\TextInput::make('last_name')->required(),
        ]);
}
```

Then when trying to edit this resource, the data which is provided to the model or `handleRecordUpdate()` method, is only the `last_name`. The `Forms\Components\Placeholder::make('')` seems to be clearing the form data somehow.

When I then change the the `''` to `'placeholder'` (`Forms\Components\Placeholder::make('placeholder')`). Everything works fine and I get both `first_name` and `last_name` back.

### Expected behavior

The given form data should be:

```
array:16 [▼
  "first_name" => "John"
  "last_name" => "Doe"
]
```

### Steps to reproduce

Create a Form schema for a resource with:

```
public static function form(Form $form): Form
{
    return $form
        ->schema([
            Forms\Components\TextInput::make('first_name')->required(),
            Forms\Components\Placeholder::make(''),
            Forms\Components\TextInput::make('last_name')->required(),
        ]);
}
```

Add the following method to the resource Edit page:

```
protected function handleRecordUpdate(Model $record, array $data): Model
{
    dd($data);
    
    return parent::handleRecordUpdate($record, $data); // TODO: Change the autogenerated stub
}
```

Then when trying to edit this resource, the data which is provided to the model or `handleRecordUpdate()` method, is only the `last_name`. 

```
array:16 [▼
  "last_name" => "Doe"
]
```

### Reproduction repository

https://github.com/none

**Comment by danharrin** [comment]
Although this is unexpected behaviour, using an empty string name as a form component name in the first place is definitely not supported. If you don't want a label, you should be using `->disableLabel()`, which hides the label except for screen readers. All fields should have internal labels for accessibility reasons.
