### ISSUE TITLE
Collapsing/expanding of repeater items are broken in relation manager

### ISSUE THREAD

**Issue by bokoch** [filamentphp/filament#4131]
### Package

filament/forms

### Package Version

v2.16.9

### Laravel Version

v9.31.0

### Livewire Version

v2.10.7

### PHP Version

v8.1.9

### Problem description

I created repeater in relation manager, repeater is collapsible and collapsed by default.
When I created few entries (two or more) for this relation. When I click "Edit" on some entry from relation manager, it is ok, repeater items are collapsed, but when I close modal and open another entry (should not be the same entry), modal is opened, but repeater items are expanded and not collapsing on click.
And found such error in browser console:
<img width="1780" alt="image" src="https://user-images.githubusercontent.com/9802540/191542059-cef0b196-2157-4b40-83b7-fcd96b3e48f8.png">

### Expected behavior

When I open modal, repeater should be collapsed by default and collapsing/expanding should work, for all entries in relation manager table.

### Steps to reproduce

1. Created repeater inside relation manager (can be found in reproduction repository).
```
Forms\Components\Repeater::make('comments')
                    ->collapsed()
                    ->itemLabel(
                        fn($state) => $state['author'] ?? null
                    )
                    ->relationship('comments')
                    ->orderable()
                    ->schema([
                        Forms\Components\TextInput::make('author'),
                        Forms\Components\RichEditor::make('content'),
                    ])
```
2. Create few entries (two or more) for this relation. In reproduction repository, you can check readme file, you can clone repo and run project via Laravel Sail, migrations and seeder are already created, so need just to run them.
3. Click "Edit" on one item from relation manager table. This will open modal window with form, repeater items are collapsed.
4. Close modal window and then hit "Edit" button for another relation item (it is important that it is shouldn't be same item).
5. This will open modal window, but repeater items are expanded and it is not possible to collapse them with clicking on "minus" sign.

### Reproduction repository

https://github.com/bokoch/filament-issue-demo

### Relevant log output

```shell
module.esm.js:420 Uncaught TypeError: Cannot read properties of null (reading '__livewire')
    at SupportAlpine.js:53:36
    at Object.get (module.esm.js:398:16)
    at Object.get (module.esm.js:308:14)
    at eval (eval at <anonymous> (module.esm.js:471:14), <anonymous>:4:79)
    at module.esm.js:489:21
    at V (module.esm.js:409:12)
    at module.esm.js:2623:17
    at n (module.esm.js:1609:16)
    at Object.effect (module.esm.js:1584:5)
    at r (module.esm.js:48:33)
```

**Comment by twaydevelopment** [comment]
Similar error.
Also the fields remain empty.
I have to reload the page.

![image](https://user-images.githubusercontent.com/84721502/195808109-ba1c3cae-b238-4143-a1a6-baaeb7efe780.png)

**Comment by bokoch** [comment]
Currently I'm using such fix:
<img width="790" alt="image" src="https://user-images.githubusercontent.com/9802540/195965067-c89707fc-a3a0-40a6-ad36-4ccedd2c2a16.png">
```
x-init="
    // https://github.com/filamentphp/filament/issues/3665
    this.wire = $wire.__instance
    $watch('isOpen', () => {
        if (isOpen) {
            return
        }
        $wire.mountedTableAction = null
        // https://github.com/filamentphp/filament/pull/3525
        this.wire.set('mountedTableAction', null)
    })
"
```
I found it here in older issues. As I understand, It is refreshing table on modal close action. And it is worked for me. However it is not really good solution, because I need to override tables/index.blade.php file, and with updating of package need to manually update that file. Maybe there is a better solution, but for now I using this one.

**Comment by awcodes** [comment]
@danharrin Seems this issue caused by having wire:key on the modal itself. It's also affecting page actions too. 

Is there a specific reason to have the wire:key on the modals with mounted actions?

**Comment by danharrin** [comment]
Does #4764 fix this?

**Comment by awcodes** [comment]
Yea. I think this is the same issue as the color picker issue.

**Comment by bokoch** [comment]
Yes, I just checked it, and it is working well now, thanks.

**Comment by twaydevelopment** [comment]
When creating a new record and then opening a record from the table (once), there is still an error

If you just open the created records, everything is fine
![image](https://user-images.githubusercontent.com/84721502/200864123-657a48fd-2a60-463d-915a-da36d8d47852.png)

**Comment by awcodes** [comment]
We are working on this at the moment and hope to have a solution soon.

**Comment by danharrin** [comment]
Please check again in the latest release

**Comment by twaydevelopment** [comment]
yes it's working now

**Comment by michabbb** [comment]
hi there,

i have the latest release: 

filament: v2.16.66
livewire: v2.11.2
PHP: 8.2

and created a simple "HasMany" relation. searching for them works, but when I click on one in the drop-down, nothing happens. clicking again on "Associate" shows me the same error as mentioned here:

```
SupportAlpine.js:49 Alpine: Cannot reference "$wire" outside a Livewire component.
(anonymous) @ SupportAlpine.js:49
get @ module.esm.js:398
get @ module.esm.js:308
getOptionsUsing @ VM118129:12
(anonymous) @ module.esm.js:28150
c @ module.esm.js:2
(anonymous) @ module.esm.js:2
(anonymous) @ module.esm.js:2
bc @ module.esm.js:2
a @ module.esm.js:2
(anonymous) @ module.esm.js:2
(anonymous) @ module.esm.js:2
(anonymous) @ module.esm.js:28151
(anonymous) @ module.esm.js:28140
c @ module.esm.js:2
(anonymous) @ module.esm.js:2
(anonymous) @ module.esm.js:2
bc @ module.esm.js:2
a @ module.esm.js:2
(anonymous) @ module.esm.js:2
(anonymous) @ module.esm.js:2
(anonymous) @ module.esm.js:28142
(anonymous) @ module.esm.js:28123
c @ module.esm.js:2
(anonymous) @ module.esm.js:2
(anonymous) @ module.esm.js:2
bc @ module.esm.js:2
a @ module.esm.js:2
(anonymous) @ module.esm.js:2
(anonymous) @ module.esm.js:2
(anonymous) @ module.esm.js:2207
SupportAlpine.js:53 Uncaught (in promise) TypeError: Cannot read properties of null (reading '__livewire')
    at SupportAlpine.js:53:36
    at Object.get (module.esm.js:398:16)
    at Object.get (module.esm.js:308:14)
    at getOptionsUsing (eval at r (module.esm.js:471:14), <anonymous>:12:29)
    at module.esm.js:28150:22
    at c (module.esm.js:2:1)
    at Generator.<anonymous> (module.esm.js:2:1)
    at Generator.next (module.esm.js:2:1)
    at bc (module.esm.js:2:1)
    at a (module.esm.js:2:1)
```

![image](https://user-images.githubusercontent.com/3524595/215432926-c416f6ec-bb5a-4931-9d64-80e7d02c922a.png)

all issues where this error is mentioned people say "it´s working now", but for me, it´s not. 
so I don´t know if I am doing something wrong here ;-( would be happy if someone could help.

**Comment by danharrin** [comment]
@michabbb the error is not the same, you are not using the repeater. Please open an issue with a reproduction repository where we can reproduce the error.

**Comment by michabbb** [comment]
@danharrin okay, will do, thanks

**Comment by michabbb** [comment]
@danharrin after debugging a whole day, i found my problem, would be happy, if you could take a look into it 😢 
https://github.com/filamentphp/filament/commit/e9db7340c3ea06093dd1da9ff51de587b94db9c7#commitcomment-98675845
