### ISSUE TITLE
Chart.js plugin support, chartjs-plugin-annotation not load

### ISSUE THREAD

**Issue by lam0819** [filamentphp/filament#4182]
Package
filamentphp/filament

Package Version
^2.0

Laravel Version
^9.0

PHP Version
8.1.7

Problem description

 In my case,  I want to use chartjs plugin, chartjs-plugin-annotation and chartjs-plugin-datalabels.

1. originally designed, the filament chart widget cannot add the plugin.
2. I extend a new blade to support the plugin
3. finally, I can add "plugins: [ChartDataLabels]", it shows correctly.
4. however, I figure out that chartjs-plugin-annotation is not work under "alpinejs" + "livewire"

is there any idea why this happen?

Here is the code.

`
<x-filament::widget class="filament-widgets-chart-widget2">
    <x-filament::card>

        @once
            <script src="https://cdn.jsdelivr.net/npm/chart.js@3.9.1/dist/chart.min.js"></script>
            <script src="https://cdnjs.cloudflare.com/ajax/libs/chartjs-plugin-annotation/2.0.1/chartjs-plugin-annotation.min.js">
            </script>
            <script src="https://cdn.jsdelivr.net/npm/chartjs-plugin-datalabels@2.1.0"></script>
        @endonce

        <div class="w-full">
            <canvas id="myChart" class="rounded-lg bg-white p-8"></canvas>
        </div>
        <script>
            const options = {
                plugins: {
                    autocolors: false,
                    annotation: {
                        annotations: {
                            line1: {
                                type: 'line',
                                yMin: 60,
                                yMax: 60,
                                borderColor: 'rgb(255, 99, 132)',
                                borderWidth: 2
                            },
                            label1: {
                                type: 'label',
                                xValue: 2.5,
                                yValue: 60,
                                backgroundColor: 'rgba(245,245,245)',
                                content: ['This is my text', 'This is my text, second line'],
                                font: {
                                    size: 18
                                }
                            }
                        }
                    }
                }
            };
            const config = {
                plugins: [ChartDataLabels],
                type: 'line',
                data: {
                    labels: ['January', 'February', 'March', 'April', 'May', 'June', 'July'],
                    datasets: [{
                        label: 'My First Dataset',
                        data: [65, 59, 80, 81, 56, 55, 40],
                        fill: false,
                        borderColor: 'rgb(75, 192, 192)',
                        tension: 0.1,
                        datalabels: {
                            color: 'red'
                        }
                    }]
                },
                options
            };

            const myChart = new Chart('myChart', config);
            // const myChart2 = new Chart('chart2', config);
        </script>

        <div wire:ignore   x-data="{
            init() { let chart = new Chart('chart2', config); }
        }" class="w-full">
            <canvas id="chart2" class="rounded-lg bg-white p-8"></canvas>
        </div>

        <div wire:ignore   x-data="{
            init() { let chart = new Chart(this.$refs.canvas.getContext('2d'), config); }
        }" class="w-full">
            <canvas x-ref="canvas" class="rounded-lg bg-white p-8"></canvas>
        </div>

    </x-filament::card>
</x-filament::widget>
`

here is the result , First one is correct, other all wrong

![image](https://user-images.githubusercontent.com/68211972/191891125-49206ed7-d7fa-4bae-9214-9ddd82c10e8c.png)

_Originally posted by @lam0819 in https://github.com/filamentphp/filament/discussions/4155_

**Comment by zepfietje** [comment]
Hey @lam0819! Could you open an issue using the bug report template and fill in all required details? This would allow us to help you better. 🙂

**Comment by lam0819** [comment]
Let me take some time to create a Reproduction repository

**Comment by lam0819** [comment]
Let me take some time to create a Reproduction repository

**Comment by danharrin** [comment]
Honestly I don't think this a Filament bug, it's just an issue with your implementation. Discussion should be continued in #4155, not here. You can post the reproduction repository there when you create it.
