### ISSUE TITLE
[FILAMENT-FORMS] Filepond.js not working on FileUpload Components

### ISSUE THREAD

**Issue by andre-arc** [filamentphp/filament#4190]
### Package

filament/forms

### Package Version

v2.0.0

### Laravel Version

v8.75

### Livewire Version

v2.0.0

### PHP Version

PHP 8.1.10

### Problem description

file upload component just displaying html input type file

### Expected behavior

file upload supposed  displaying plugin filepond.js with file preview

### Steps to reproduce

- run laravel on Reproduction repository

### Reproduction repository

https://github.com/andre-arc/filament-formbuilder.git

### Relevant log output

```shell
app.js:3195 
        
       Uncaught TypeError: Cannot read properties of undefined (reading 'directive')
    at ./vendor/filament/forms/dist/module.esm.js (app.js:3195:54)
    at __webpack_require__ (app.js:3573:41)
    at ./resources/js/app.js (app.js:2981:96)
    at __webpack_require__ (app.js:3573:41)
    at app.js:3707:64
    at __webpack_require__.O (app.js:3612:23)
    at app.js:3709:53
    at app.js:3711:12
./vendor/filament/forms/dist/module.esm.js @ app.js:3195
__webpack_require__ @ app.js:3573
./resources/js/app.js @ app.js:2981
__webpack_require__ @ app.js:3573
(anonymous) @ app.js:3707
__webpack_require__.O @ app.js:3612
(anonymous) @ app.js:3709
(anonymous) @ app.js:3711
index.js:85 
        
```

**Comment by andre-arc** [comment]
![image](https://user-images.githubusercontent.com/11828823/192152310-986101bc-7f58-4bd8-b915-db597956137c.png)

this result using FileUpload Components

**Comment by danharrin** [comment]
You **must** call `$this->form->fill()` from `mount()` for every single form you build. It's in the complete docs examples on the Getting Started page.

**Comment by andre-arc** [comment]
still not working after calling `form->fill() ` on method `mount` with the same error log
it's there something wrong with `vendor/filament/forms/dist/module.esm.js`

**Comment by andre-arc** [comment]
sorry i mistaken load livewire scripts on bottom view file. in your documentation you put livewire script on top of document.
