### ISSUE TITLE
Use Blade svg helper instead of components for icons

### ISSUE THREAD

**Issue by danharrin** [filamentphp/filament#4194]
### Discussed in https://github.com/filamentphp/filament/discussions/3965

<div type='discussions-op-text'>

<sup>Originally posted by **ianlandsman** September 12, 2022</sup>
Using Blade Icons default component calls adds a huge performance hit when you have large icon libraries like Font Awesome. We've seen 200-400ms increases in page load time when using blade-icons with these large libraries. The Blade Icons docs don't mention this that I've seen but the config file does (https://github.com/blade-ui-kit/blade-icons/blob/1.x/config/blade-icons.php#L158)

Filament Notifications use the Blade Icons component syntax and so notifications break for anyone using the library with Blade Icons component syntax disabled. As Notifications don't have any particular need to use the component syntax as they are internal calls I suggest moving to the directive syntax (https://github.com/blade-ui-kit/blade-icons/blob/1.x/README.md?plain=1#L464) which has no performance penalties. </div>

**Comment by tanthammar** [comment]
When the time comes to start with this task, I made a branch that you can merge and hopefully save some time.
Based on v2.13.20
https://github.com/tanthammar/filament/tree/svg-blade-icons

**Comment by zepfietje** [comment]
Thanks, @tanthammar.

I see in some places you wrapped the `@svg` directive in an additional `span` tag to add attributes to it? Attributes can also be passed as an argument to the `@svg` directive, so it doesn't need any additional wrapping elements.

Also, there's a few places where indentation needs to be fixed in your fork. 🙂

@danharrin, would it be cool if @tanthammar opened a PR that we can tag with the v3 label, or do you think we get to it ourselves when working on v3?

**Comment by tanthammar** [comment]
@zepfietje "I see in some places you wrapped the @svg directive in an additional span tag to add attributes to it? Attributes can also be passed as an argument to the @svg directive, so it doesn't need any additional wrapping elements."

I tried adding them to the @svg directive, but decided to go for a span where needed.  
It was the only common denominator to keep the code style consistent in all places.

A `<span>` doesn't cost anything. You get to keep code hints from your ide. The ide color format works. You don't have to mess with escaping chars or concatenating strings with vars...

For instance adding `x-cloak` doesn't work.
```blade
@svg($icon, 'some classes', [x-cloak]) //x-cloak is never rendered

{{ svg($icon)->class('some classes')->x-cloak()  }} //error due to 'x-'
```

Another example
```blade
//before
<x-heroicon-o-check
      x-show="getStepIndex(step) > {{ $loop->index }}"
      x-cloak
      class="w-5 h-5 text-white"
/>

//tricky
@svg('heroicon-o-check', [
    'class' => 'w-5 h-5 text-white',
    'x-show' => 'getStepIndex(step) > ' . $loop->index,
    'x-cloak', //what to do here?
)

//my choice
<span x-show="getStepIndex(step) > {{ $loop->index }}" x-cloak>
    @svg('heroicon-o-check', 'w-5 h-5 text-white')
</span>
```

Same thing, feels awkward 
```blade
//before
<x-heroicon-o-search class="w-5 h-5" wire:loading.remove.delay wire:target="search" />

//not nice
@svg('heroicon-o-search', 'w-5 h-5', [
    'wire:target' => 'search',
    'wire:loading.remove.delay', /should we set this to => true?
])

//my choice
<span wire:loading.remove.delay wire:target="search">
    @svg('heroicon-o-search', 'w-5 h-5')
</span>
```

```blade
//before
<x-dynamic-component
    :component="$icon"
    :wire:loading.remove.delay="$hasLoadingIndicator"
    :wire:target="$hasLoadingIndicator ? $loadingIndicatorTarget : false"
    :class="$iconClasses"
/>

//ok this will work, but it looks so weird and all ide colors, and auto-completion are gone.
@svg($icon, $iconClasses, [
    ':wire:loading.remove.delay' => '$hasLoadingIndicator'
    ':wire:target' => '$hasLoadingIndicator ? $loadingIndicatorTarget : false'
])

//so I thought this was better here too
<span 
    :wire:loading.remove.delay="$hasLoadingIndicator" 
    :wire:target="$hasLoadingIndicator ? $loadingIndicatorTarget : false"
>
    @svg($icon, $iconClasses)
</span>
```

I can go on with more examples but I hope you see why I choose a `span`

But this branch was only my way of trying to help. You're the boss.

**Comment by danharrin** [comment]
`<span>` wrapper is perfect for this.
