### ISSUE TITLE
File upload isn't cleared after create and add another 

### ISSUE THREAD

**Issue by ElenaMainerici** [filamentphp/filament#4207]
### Package

filament/filament

### Package Version

^2.15

### Laravel Version

^9.19

### PHP Version

^8.0.2

### Problem description

file upload isn't cleared after create and add another 

### Expected behavior

Clear files after submit create and add another
<img width="1027" alt="Screenshot 2022-09-26 at 15 52 24" src="https://user-images.githubusercontent.com/5088477/192294331-e1a21e09-2bbf-47b2-bb53-b60779cb9672.png">

### Steps to reproduce

Create a Product
Add a image
Click Create & Create Another

 "php": "^8.0.2",
"doctrine/dbal": "^3.3",
"filament/filament": "^2.0",

### Reproduction repository

https://github.com/filamentphp/demo

**Comment by ElenaMainerici** [comment]
Can be tested here: https://github.com/filamentphp/demo

**Comment by awcodes** [comment]
@danharrin 

I think i have this fixed, but there is also an issue related to this with the markdown component that is doing the same thing where is it not clearing after clicking create and create another.

The markdown component is erroring causing it to not update it's internal state.

Would you like me to include that fix in the PR for this issue or create it as a separate PR.

**Comment by zepfietje** [comment]
Preferably keep PRs separate for different issues, @awcodes.

**Comment by awcodes** [comment]
Fair, but there isn't another actual issue for the markdown editor, and since it's related to the same issue I wasn't sure.

**Comment by zepfietje** [comment]
Fair, in this case both could be fine I guess.
