### ISSUE TITLE
An empty RelationResource causes a "Multiple root elements detected" livewire error which causes sideeffects

### ISSUE THREAD

**Issue by dissto** [filamentphp/filament#4218]
### Package

filament/filament

### Package Version

^2.0

### Laravel Version

9.31.0

### Livewire Version

^2.5

### PHP Version

8.1.6

### Problem description

An empty `RelationResource` (with no records listed) causes a console error of

`Livewire: Multiple root elements detected. This is not supported. See docs for more information https://laravel-livewire.com/docs/2.x/troubleshooting#root-element-issues div.filament-page.filament-resources-edit-record-page.filament-resources-groups.filament-resources-record-2`

This also has a side effect that the action buttons don't work on the first click. Instead you have to click it twice. After the first click, the sidebar changes color, but thats it.
I have attached a video showcasing that.

https://user-images.githubusercontent.com/11778632/192369897-c9d71059-b8f2-4037-b54b-583f3417647d.mp4

As soon as you have at least one record in a RelationResource and you refresh the page, the livewire error is gone and the button works on the first click.

### Expected behavior

To not get an error when having an empty RelationResource

### Steps to reproduce

Create a RelationResource and have it displayed without a record in that table (relation)

### Reproduction repository

https://github.com/filamentphp/demo

**Comment by danharrin** [comment]
This was already fixed by #4199, the demo just needs to be updated to the new version.
