### ISSUE TITLE
Send notifications from JavaScript

### ISSUE THREAD

**Issue by danharrin** [filamentphp/filament#4239]
### Discussed in https://github.com/filamentphp/filament/discussions/3582

<div type='discussions-op-text'>

<sup>Originally posted by **studiowizjo** August 20, 2022</sup>
How  notifications can be send from view? I tried approach like below, but without success.

```js
x-data="{
    copyUrlToClipboard() {
        navigator.clipboard.writeText('{{ $comment->scrollUrl() }}');

        $dispatch('notify.window', { //or just: 'notify'
            message: 'URL was copied to clipboard',
            status: 'success',
        });
    }
}"
```</div>

**Comment by zepfietje** [comment]
We've discussed this before in https://github.com/filamentphp/filament/pull/3424, right?

**Comment by danharrin** [comment]
I think we should mirror the PHP API with a JS object.

**Comment by zepfietje** [comment]
Or could we just build the PHP `Notification` object and call the `toArray()` method from the view? Just exploring here. 😄

**Comment by danharrin** [comment]
that wouldn't work if you wanted to use a JS variable within the message or something

**Comment by zepfietje** [comment]
Yeah that's the main concern I could come up with as well.
