### ISSUE TITLE
File did not upload on settings

### ISSUE THREAD

**Issue by lloricode** [filamentphp/filament#4289]
### Package

filament/spatie-laravel-settings-plugin

### Package Version

v2.16.18

### Laravel Version

v9.32.0

### Livewire Version

v2.10.7

### PHP Version

PHP 8.1.9

### Problem description

Expected to receive file upload using `FileUpload::make($field)` in `mutateFormDataBeforeSave` function

### Expected behavior

it will receive FileUpload data in `mutateFormDataBeforeSave`

### Steps to reproduce

kindly set this repository on your environment https://github.com/lloricode/laravel-filament-issue/tree/bugs/settings-file-upload, after this, follow steps to produce an issue/unexpected-behavior

1. open ray app
2. visit site in `/admin/manage-site`
3. upload any image
4. see result is ray app being `logo` is null

image reference:

![Screenshot_2022-09-30_14-27-48](https://user-images.githubusercontent.com/8251344/193206996-54d27712-4003-43ed-a213-0e1a6e38846d.png)

![Screenshot_2022-09-30_14-27-36](https://user-images.githubusercontent.com/8251344/193207002-f4f1a675-b98d-4119-af90-0b2d27d78531.png)

### Reproduction repository

https://github.com/lloricode/laravel-filament-issue/tree/bugs/settings-file-upload

**Comment by zepfietje** [comment]
Hey @lloricode!
I've tried to run your reproduction repository, but it seems incomplete.
`Class "Filament\Pages\SettingsPage" not found`

Could you update the repository so we can reproduce the issue easily?

**Comment by lloricode** [comment]
Hi will check it

**Comment by lloricode** [comment]
hi @zepfietje, it already fix since i updated to filament `v2.16.23`, thank you for your time
