### ISSUE TITLE
Table : empty state makes search columns disappear

### ISSUE THREAD

**Issue by Sicklou** [filamentphp/filament#4300]
### Package

filament/tables

### Package Version

v2.16.19

### Laravel Version

v9.33.0

### Livewire Version

v2.10.7

### PHP Version

8.1.0

### Problem description

The header row with the search inputs disappears and make the all things stuck.

Before :
![image](https://user-images.githubusercontent.com/8366863/193300128-b1f37ca7-c546-49bd-a2b6-8ee7d4486538.png)

After : 
![image](https://user-images.githubusercontent.com/8366863/193300204-d0042b67-01d4-44bc-a1ee-34e208da5c1d.png)

### Expected behavior

That the header is isolated from the rows of data.

Event when there is no search inputs, I think it's better UI/UX that keep the header visible.

### Steps to reproduce

Nothing particular, just make a search that doesn't give any data.

### Reproduction repository

No reproduction repository

**Comment by danharrin** [comment]
Duplicate of #4224

**Comment by Sicklou** [comment]
Sorry I didn't take a look
