### ISSUE TITLE
Autofocus inside a wizard step gets ignored

### ISSUE THREAD

**Issue by dissto** [filamentphp/filament#4301]
### Package

filament/filament

### Package Version

^2.0

### Laravel Version

9.32.0

### Livewire Version

^2.5

### PHP Version

8.1.6

### Problem description

If you set `autofocus->()` to an input inside a step inside a wizard - it will be ignored.

### Expected behavior

To set autofocus properly

### Steps to reproduce

Set autofocus() on any input inside a `\Step`

### Reproduction repository

https://github.com/dissto/filament

**Comment by danharrin** [comment]
Fixed by #4408.
