### ISSUE TITLE
You are not able to manually change the value of a `TimePicker` input

### ISSUE THREAD

**Issue by dissto** [filamentphp/filament#4303]
### Package

filament/filament

### Package Version

^2.0

### Laravel Version

9.32.0

### Livewire Version

^2.5

### PHP Version

8.1.6

### Problem description

You cannot manually change the time in the input field (TimePicker). You are forced to use the little input mask that pops up. I cannot go inside the input and select a time and manually enter it (which is by far easier than clicking those tiny little arrows).

### Expected behavior

You should be able to manually change the time by selecting the inputs values. 

### Steps to reproduce

Create a TimePicker input and try to change its value 

### Reproduction repository

https://github.com/dissto/filament

**Comment by danharrin** [comment]
This isn't a bug, our TimePicker is an extension of our DateTimePicker and it doesn't have this functionality built. If you want a text input, use a `TextInput` with `mask()`
