### ISSUE TITLE
Filament retrieves wrong image urls from filestorage

### ISSUE THREAD

**Issue by Arturexe** [filamentphp/filament#4315]
### Package

filament/filament

### Package Version

v2.0.0

### Laravel Version

v9.19

### PHP Version

8.0.18

### Problem description

I've set up a FileUpload form, linked my storage and correctly uploaded an image to it. But when I created a ImageColumn, the images were shown as broken. The image urls observed in browser were `http://localhost/img-id...` but my port is 8000, so I navigated to `http://localhost:8000/img-id...` and the browser displayed the image correctly.

The problem could be resolved by changing .env from:

`APP_URL=http://localhost`
to
`APP_URL=http://localhost:8000`

### Expected behavior

-

### Steps to reproduce

-

### Reproduction repository

-

**Comment by danharrin** [comment]
Maybe I'm misunderstanding, but how is this a bug with Filament if the APP_URL was wrong...

**Comment by Arturexe** [comment]
For me, filament is the first app that seems to require an update to the APP_URL variable from default in a dev environment. It broke the images in the admin panel for me and there was no information of how to solve it. If this can be declared a bug or not is not obvious to me either. Should it not behave like the rest of laravel, processing the default url and the current port by itself?

**Comment by danharrin** [comment]
we don't explicitly use the APP_URL anywhere, we use the Storage facade to generate URLs
