### ISSUE TITLE
SlideOver appearance animation

### ISSUE THREAD

**Issue by JohnnyMaynne** [filamentphp/filament#4319]
### Package

filament/filament

### Package Version

v2.16.19

### Laravel Version

v9.33

### Livewire Version

v2.10.7

### PHP Version

v8.1.3

### Problem description

Slideover spawn animation starts from the left

Video:  https://www.dropbox.com/s/qxw0s3saeziq5gq/111.mov?dl=0

### Expected behavior

Slideover spawn animation starts from the right

### Steps to reproduce

Add to page action slideOver() methode

### Reproduction repository

https://github.com/not-link

**Comment by danharrin** [comment]
I can't reproduce this myself, and you've given no reproduction repository or code examples.

**Comment by andrewdwallo** [comment]
I can confirm that this does happen sometimes. I do not know why. But I did change this in the modal:
```js
x-show="isShown"
x-transition:enter="duration-300"
x-transition:leave="duration-300"
@if ($width === MaxWidth::Screen)
@elseif ($slideOver)
       x-transition:enter-start="translate-x-full rtl:-translate-x-full"
       x-transition:enter-end="translate-x-0"
       x-transition:leave-start="translate-x-0"
       x-transition:leave-end="translate-x-full rtl:-translate-x-full"
@else
```

To this:
```js
x-show="isShown"
x-transition:enter-start="duration-300"
x-transition:enter-end="duration-300"
x-transition:leave-start="duration-300"
x-transition:leave-end="duration-300"
@if ($width === MaxWidth::Screen)
@elseif ($slideOver)
       x-transition:enter-start="translate-x-full rtl:-translate-x-full"
       x-transition:enter-end="translate-x-0"
       x-transition:leave-start="translate-x-0"
       x-transition:leave-end="translate-x-full rtl:-translate-x-full"
@else
```
Which is pretty much the same right? But it causes the issue to go way.

**Comment by danharrin** [comment]
Can you make a PR please @andrewdwallo?

**Comment by andrewdwallo** [comment]
Yeah sure! I am not on the computer right now but I will first thing tomorrow.

**Comment by andrewdwallo** [comment]
@danharrin I noticed the issue occurred specifically when having an href element inside the modal, if that tells you anything of what  might be causing it. But here is more info in the meantime: https://discord.com/channels/883083792112300104/1138244989495824495/1193704489044168866
