### ISSUE TITLE
Performance issues on tables with disabled reordering

### ISSUE THREAD

**Issue by LukasFreyCZ** [filamentphp/filament#4321]
### Package

filament/tables

### Package Version

v2.16.17

### Laravel Version

v.9.31

### Livewire Version

v2.10.7

### PHP Version

PHP 8.1

### Problem description

Table items, even if reordering is disabled, render a hidden drag & drop handle with an svg icon, causing performance issues, since each svg takes quite a lot of memory. My page load takes 1s+ with these handles.

Another thing, I think (?) every icon also has a filament-loader-icon, which basically is present everywhere. So when I set `->icon(null)` on the table actions to reduce the size of loaded SVGs, it would still load and hide this loader icon SVG. Resulting in none to minimal improvements.

### Expected behavior

Drag & drop handles shouldn't render at all.

### Steps to reproduce

Render a filament table and disable reordering

### Reproduction repository

https://github.com/no-link

**Comment by zepfietje** [comment]
@danharrin, would it be possible to completely remove the reorder icons when reordering has not been enabled?

**Comment by danharrin** [comment]
I think we did that originally and then it caused DOM diffing issues so someone changed it in a PR

**Comment by zepfietje** [comment]
Could those diffing issues be resolved by adding proper `wire:key` attributes?

**Comment by danharrin** [comment]
wire:key doesn't improve things in this case, and we can't wrap a <div> around a table cell. So we need to conditionally hide the content, which is ugly - #4416
